topics = {
    "Getting Started".lower() : "https://www.programiz.com/python-programming/first-program",
    "Keywords and Identifiers".lower() : "https://www.programiz.com/python-programming/keywords-identifier",
    "Statements & Comments".lower() : "https://www.programiz.com/python-programming/statement-indentation-comments",
    "Python Variables".lower() : "https://www.programiz.com/python-programming/variables-constants-literals",
    "Python Data types".lower() : "https://www.programiz.com/python-programming/variables-datatypes",
    "Python Type Conversion".lower() : "https://www.programiz.com/python-programming/type-conversion-and-casting",
    "Python I/O and import".lower() : "https://www.programiz.com/python-programming/input-output-import",
    "Python Operators".lower() : "https://www.programiz.com/python-programming/operators",
    "Python Namespace".lower() : "https://www.programiz.com/python-programming/namespace",
    "Python if...else".lower() : "https://www.programiz.com/python-programming/if-elif-else",
    "Python for Loop".lower() : "https://www.programiz.com/python-programming/for-loop",
    "Python while Loop".lower() : "https://www.programiz.com/python-programming/while-loop",
    "Python break and continue".lower() : "https://www.programiz.com/python-programming/break-continue",
    "Python Pass".lower() : "https://www.programiz.com/python-programming/pass-statement",
    "Python Functions".lower() : "https://www.programiz.com/python-programming/function",
    "Function Argument".lower() : "https://www.programiz.com/python-programming/function-argument",
    "Python Recursion".lower() : "https://www.programiz.com/python-programming/recursion",
    "Anonymous Function".lower() : "https://www.programiz.com/python-programming/anonymous-function",
    "Global, Local and Nonlocal".lower() : "https://www.programiz.com/python-programming/global-local-nonlocal-variables",
    "Python Global Keyword".lower() : "https://www.programiz.com/python-programming/global-keyword",
    "Python Modules".lower() : "https://www.programiz.com/python-programming/modules",
    "Python Package".lower() : "https://www.programiz.com/python-programming/package",
    "Python Numbers".lower() : "https://www.programiz.com/python-programming/numbers",
    "Python List".lower() : "https://www.programiz.com/python-programming/list",
    "Python Tuple".lower() : "https://www.programiz.com/python-programming/tuple",
    "Python String".lower() : "https://www.programiz.com/python-programming/string",
    "Python Set".lower() : "https://www.programiz.com/python-programming/set",
    "Python Dictionary".lower() : "https://www.programiz.com/python-programming/dictionary",
    "Python File Operation".lower() : "https://www.programiz.com/python-programming/file-operation",
    "Python Directory".lower() : "https://www.programiz.com/python-programming/directory",
    "Python Exception".lower() : "https://www.programiz.com/python-programming/exceptions",
    "Python Exception Handling".lower() : "https://www.programiz.com/python-programming/exception-handling",
    "Python User-defined Exception".lower() : "https://www.programiz.com/python-programming/user-defined-exception",
    "Python OOP".lower() : "https://www.programiz.com/python-programming/object-oriented-programming",
    "Python Class".lower() : "https://www.programiz.com/python-programming/class",
    "Python Inheritance".lower() : "https://www.programiz.com/python-programming/inheritance",
    "Multiple Inheritance".lower() : "https://www.programiz.com/python-programming/multiple-inheritance",
    "Operator Overloading".lower() : "https://www.programiz.com/python-programming/operator-overloading",
    "Python Iterator".lower() : "https://www.programiz.com/python-programming/iterator",
    "Python Generator".lower() : "https://www.programiz.com/python-programming/generator",
    "Python Closure".lower() : "https://www.programiz.com/python-programming/closure",
    "Python Decorators".lower() : "https://www.programiz.com/python-programming/decorator",
    "Python Property".lower() : "https://www.programiz.com/python-programming/property",
    "Python RegEx".lower() : "https://www.programiz.com/python-programming/regex",
    "Python Examples".lower() : "https://www.programiz.com/python-programming/examples",
    "Python datetime Module".lower() : "https://www.programiz.com/python-programming/datetime",
    "Python datetime.strftime()".lower() : "https://www.programiz.com/python-programming/datetime/strftime",
    "Python datetime.strptime()".lower() : "https://www.programiz.com/python-programming/datetime/strptime",
    "Current date & time".lower() : "https://www.programiz.com/python-programming/datetime/current-datetime",
    "Get current time".lower() : "https://www.programiz.com/python-programming/datetime/current-time",
    "Timestamp to datetime".lower() : "https://www.programiz.com/python-programming/datetime/timestamp-datetime",
    "Python time Module".lower() : "https://www.programiz.com/python-programming/time",
    "Python time.sleep()".lower() : "https://www.programiz.com/python-programming/time/sleep",
}