import pyautogui as pg
def msg():
    time = 0.01
    pg.typewrite("Hello sir ...",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("New layouts launch on",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Wardha road",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Shankarpur",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Buttibori 2nd phase MIDC",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Samruddhi Highway",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("*NIT | NMRDA | RL |*",time)
    pg.hotkey("shift","enter")
    pg.typewrite("SANCTIONED PROPERTY",time)
    pg.hotkey("shift","enter")
    pg.typewrite("*Ready for Construction*",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("Rates are from 650/- sqft to 2000/-sqft ",time)
    pg.hotkey("shift","enter")
    pg.typewrite("With 30 to 42 months of Emi ",time)
    pg.hotkey("shift","enter")
    pg.typewrite("Contact for more info 9588464281",time)
    pg.hotkey("shift","enter")
    pg.typewrite("Thank you",time)
    pg.hotkey("shift","enter")
    pg.typewrite("Regards - Abhishek Telmore ",time)
    pg.hotkey("shift","enter")
    pg.typewrite("==================================",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("=> Residential purpose ",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Commercial purpose",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Investment purpose ",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("Available in clear title",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite(".....Payment facility....",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("=> Bank finance ( Nationalized Bank)",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> Cash Payment.",time)
    pg.hotkey("shift","enter")
    pg.typewrite("=> EMI",time)
    pg.hotkey("shift","enter")
    pg.hotkey("shift","enter")
    pg.typewrite("Contact us for any queris:",time)
    pg.hotkey("shift","enter")
    pg.typewrite("+91 95884 64281",time)
    pg.press("enter")