import pyautogui as p
delay = 0
def msg():
    p.typewrite(f"Hello dear,",delay)
    p.hotkey("shift","enter")
    p.hotkey("shift","enter")
    p.typewrite("Im sachin palekar from palekar jwellers",delay)
    p.hotkey("shift","enter")
    p.hotkey("shift","enter")
    p.typewrite("We expect your blessing more than anything on our Palekar jwellery shop. ",delay)
    p.hotkey("shift","enter")
    p.typewrite("Let us all enjoy the holy occasion with your sweet presence.",delay)
    p.hotkey("shift","enter")
    p.hotkey("shift","enter")
    p.typewrite("Address:- seminary hills, surendragarh, Gupta chowk, Near shani mandir, Nagpur 440006",delay)
    p.hotkey("shift","enter")
    p.hotkey("shift","enter")
    p.typewrite("Contact no. : +91 84211 21816",delay)
    p.hotkey("shift","enter")
    p.typewrite("Instagram : www.instagram.com/palekar_jewellers/",delay)
    p.hotkey("shift","enter")
    p.typewrite("Must Watch: https://www.youtube.com/watch?v=e5cIKxamLZc",delay)
    p.hotkey("shift","enter")
    p.hotkey("shift","enter")
    p.typewrite("Palekar Jwellers Promotion Managed by GREEN CAM ENTERTAINMENT",delay)
    p.press("enter")