Network = {
               "AT" :"Airtel India",
               "CG" :"BSNL Mobile",
               "DP" :"PMTNL (DOLPHIN)",
               "AV" :"AEROVOYCE (MNVO Type)",
               "RJ" :"Reliance Jio",
               "VI" :"Vodafone Idea",
               "ETE":"tisalat India",
               "SR" :"subrin Rintel",
               "STS":"Tel",
               "LM" :"Loop Mobile",
               "RC" :"Reliance Mobile CDMA",
               "VD" :"Videocon Telecom",
               "MT" :"MTS India",
               "RG" :"Reliance Mobile GSM",
               "AC" :"AIRCEL",
               "TD" :"TATA DOCOMO",
               "TN" :"telenor",
               "@@" :"invalid input"
          }
          
States = {
              "AP" : "Andhra Pradesh & Telangana",
              "AS" :"Assam",
              "BR" :"Bihar & Jharkhand",
              "DL" :"Delhi",
              "GJ" :"Gujarat",
              "HR" :"Haryana",
              "HP" :"Himachal Pradesh",
              "JK" :"Jammu and Kashmir",
              "KA" :"Karnataka",
              "KL" :"Kerala & Lakshadweep",
              "KO" :"Kolkata",
              "MP" :"Madhya Pradesh & Chhattisgarh",
              "MH" :"Maharashtra & Goa",
              "MU" :"Mumbai",
              "NE" :"North East",
              "OR" :"Odisha",
              "PB" :"Punjab",
              "RJ" :"Rajasthan",
              "TN" :"Tamil Nadu",
              "UE" :"UP (East)",
              "UW" :"UP (West)",
              "WB" :"West Bengal",
              "@@" :"invalid input",
           }