words = {
	'a' : 'ए' ,
	'abandon' : 'छोड़ देना' ,
	'ability' : 'योग्यता' ,
	'able' : 'योग्य' ,
	'abortion' : 'गर्भपात' ,
	'about' : 'के बारे में' ,
	'above' : 'के ऊपर' ,
	'abroad' : 'विदेश' ,
	'absence' : 'अनुपस्थिति' ,
	'absolute' : 'शुद्ध' ,
	'absolutely' : 'बिल्कुल' ,
	'absorb' : 'सोख लेना' ,
	'abuse' : 'गाली देना' ,
	'academic' : 'शैक्षिक' ,
	'accept' : 'स्वीकार करें' ,
	'access' : 'पहुंच' ,
	'accident' : 'दुर्घटना' ,
	'accompany' : 'साथ' ,
	'accomplish' : 'समाप्त करना' ,
	'according' : 'अनुसार' ,
	'account' : 'हेतु' ,
	'accurate' : 'शुद्ध' ,
	'accuse' : 'आरोप' ,
	'achieve' : 'प्राप्त करना' ,
	'achievement' : 'उपलब्धि' ,
	'acid' : 'अम्ल' ,
	'acknowledge' : 'स्वीकार करना' ,
	'acquire' : 'अधिग्रहण करना' ,
	'across' : 'आर - पार' ,
	'act' : 'कार्य' ,
	'action' : 'कार्य' ,
	'active' : 'सक्रिय' ,
	'activist' : 'कार्यकर्ता' ,
	'activity' : 'गतिविधि' ,
	'actor' : 'अभिनेता' ,
	'actress' : 'अभिनेत्री' ,
	'actual' : 'वास्तविक' ,
	'actually' : 'वास्तव में' ,
	'ad' : 'विज्ञापन' ,
	'adapt' : 'अनुकूल बनाना' ,
	'add' : 'जोड़ें' ,
	'addition' : 'योग' ,
	'additional' : 'अतिरिक्त' ,
	'address' : 'पता' ,
	'adequate' : 'पर्याप्त' ,
	'adjustment' : 'समायोजन' ,
	'administration' : 'प्रशासन' ,
	'administrator' : 'प्रशासक' ,
	'admire' : 'प्रशंसा करना' ,
	'admission' : 'प्रवेश' ,
	'admit' : 'स्वीकार करना' ,
	'adolescent' : 'किशोर' ,
	'adopt' : 'अपनाने' ,
	'adult' : 'वयस्क' ,
	'advance' : 'अग्रिम' ,
	'advanced' : 'उन्नत' ,
	'advantage' : 'फायदा' ,
	'adventure' : 'साहसिक' ,
	'advertising' : 'विज्ञापन' ,
	'advice' : 'सलाह' ,
	'advise' : 'सलाह देना' ,
	'advocate' : 'वकील' ,
	'affair' : 'मामला' ,
	'affect' : 'चाहना' ,
	'afford' : 'खर्च करना' ,
	'afraid' : 'डरा हुआ' ,
	'African' : 'अफ़्रीकी' ,
	'African-American' : 'अफ्रीकी अमेरिकी' ,
	'after' : 'उपरांत' ,
	'afternoon' : 'दोपहर' ,
	'again' : 'फिर' ,
	'against' : 'के खिलाफ' ,
	'age' : 'उम्र' ,
	'agency' : 'एजेंसी' ,
	'agenda' : 'कार्यसूची' ,
	'agent' : 'एजेंट' ,
	'aggressive' : 'आक्रामक' ,
	'ago' : 'पहले' ,
	'agree' : 'इस बात से सहमत' ,
	'agreement' : 'समझौता' ,
	'agricultural' : 'कृषि' ,
	'ah' : 'एएच' ,
	'ahead' : 'आगे' ,
	'aid' : 'सहायता' ,
	'aide' : 'सहयोगी' ,
	'AIDS' : 'एड्स' ,
	'aim' : 'लक्ष्य' ,
	'air' : 'वायु' ,
	'aircraft' : 'हवाई जहाज' ,
	'airline' : 'एयरलाइन' ,
	'airport' : 'हवाई अड्डा' ,
	'album' : 'एल्बम' ,
	'alcohol' : 'शराब' ,
	'alive' : 'जीवित' ,
	'all' : 'सब' ,
	'alliance' : 'गठबंधन' ,
	'allow' : 'अनुमति' ,
	'ally' : 'मित्र' ,
	'almost' : 'लगभग' ,
	'alone' : 'अकेला' ,
	'along' : 'साथ में' ,
	'already' : 'पहले से ही' ,
	'also' : 'भी' ,
	'alter' : 'बदलने' ,
	'alternative' : 'विकल्प' ,
	'although' : 'यद्यपि' ,
	'always' : 'हमेशा' ,
	'AM' : 'पूर्वाह्न' ,
	'amazing' : 'कमाल की' ,
	'American' : 'अमेरिकन' ,
	'among' : 'के बीच में' ,
	'amount' : 'रकम' ,
	'analysis' : 'विश्लेषण' ,
	'analyst' : 'विश्लेषक' ,
	'analyze' : 'विश्लेषण' ,
	'ancient' : 'प्राचीन' ,
	'and' : 'तथा' ,
	'anger' : 'क्रोध' ,
	'angle' : 'कोण' ,
	'angry' : 'गुस्सा' ,
	'animal' : 'जानवर' ,
	'anniversary' : 'सालगिरह' ,
	'announce' : 'की घोषणा' ,
	'annual' : 'वार्षिक' ,
	'another' : 'एक और' ,
	'answer' : 'उत्तर' ,
	'anticipate' : 'पूर्वानुमान करना' ,
	'anxiety' : 'चिंता' ,
	'any' : 'कोई भी' ,
	'anybody' : 'कोई' ,
	'anymore' : 'अब' ,
	'anyone' : 'किसी को' ,
	'anything' : 'कुछ भी' ,
	'anyway' : 'वैसे भी' ,
	'anywhere' : 'कहीं भी' ,
	'apart' : 'अलग' ,
	'apartment' : 'फ्लैट' ,
	'apparent' : 'स्पष्ट' ,
	'apparently' : 'प्रतीत होना' ,
	'appeal' : 'निवेदन' ,
	'appear' : 'के जैसा लगना' ,
	'appearance' : 'दिखावट' ,
	'apple' : 'सेब' ,
	'application' : 'आवेदन' ,
	'apply' : 'लागू' ,
	'appoint' : 'नियुक्त करना' ,
	'appointment' : 'नियुक्ति' ,
	'appreciate' : 'सराहना' ,
	'approach' : 'पहुंचना' ,
	'appropriate' : 'उपयुक्त' ,
	'approval' : 'अनुमोदन' ,
	'approve' : 'मंजूर' ,
	'approximately' : 'लगभग' ,
	'Arab' : 'अरब' ,
	'architect' : 'वास्तुकार' ,
	'area' : 'क्षेत्र' ,
	'argue' : 'लोगों का तर्क है' ,
	'argument' : 'तर्क' ,
	'arise' : 'उठता' ,
	'arm' : 'हाथ' ,
	'armed' : 'हथियारबंद' ,
	'army' : 'सेना' ,
	'around' : 'चारों तरफ' ,
	'arrange' : 'व्यवस्था' ,
	'arrangement' : 'व्यवस्था' ,
	'arrest' : 'गिरफ़्तार करना' ,
	'arrival' : 'आगमन' ,
	'arrive' : 'आना' ,
	'art' : 'कला' ,
	'article' : 'लेख' ,
	'artist' : 'कलाकार' ,
	'artistic' : 'कलात्मक' ,
	'as' : 'जैसा' ,
	'Asian' : 'एशियाई' ,
	'aside' : 'अलग' ,
	'ask' : 'पूछना' ,
	'asleep' : 'सुप्त' ,
	'aspect' : 'पहलू' ,
	'assault' : 'हमला करना' ,
	'assert' : 'ज़ोर' ,
	'assess' : 'आकलन' ,
	'assessment' : 'मूल्यांकन' ,
	'asset' : 'संपत्ति' ,
	'assign' : 'असाइन' ,
	'assignment' : 'कार्यभार' ,
	'assist' : 'सहायता देना' ,
	'assistance' : 'सहायता' ,
	'assistant' : 'सहायक' ,
	'associate' : 'सहयोगी' ,
	'association' : 'संगठन' ,
	'assume' : 'मान लीजिए' ,
	'assumption' : 'कल्पना' ,
	'assure' : 'आश्वासन' ,
	'at' : 'पर' ,
	'athlete' : 'एथलीट' ,
	'athletic' : 'पुष्ट' ,
	'atmosphere' : 'वायुमंडल' ,
	'attach' : 'संलग्न करें' ,
	'attack' : 'हमला' ,
	'attempt' : 'प्रयास' ,
	'attend' : 'भाग लेना' ,
	'attention' : 'ध्यान' ,
	'attitude' : 'रवैया' ,
	'attorney' : 'प्रतिनिधि' ,
	'attract' : 'आकर्षित' ,
	'attractive' : 'आकर्षक' ,
	'attribute' : 'गुण' ,
	'audience' : 'दर्शक' ,
	'author' : 'लेखक' ,
	'authority' : 'अधिकार' ,
	'auto' : 'ऑटो' ,
	'available' : 'उपलब्ध' ,
	'average' : 'औसत' ,
	'avoid' : 'टालना' ,
	'award' : 'पुरस्कार' ,
	'aware' : 'अवगत' ,
	'awareness' : 'जागरूकता' ,
	'away' : 'दूर' ,
	'awful' : 'भयंकर' ,
	'baby' : 'शिशु' ,
	'back' : 'वापस' ,
	'background' : 'पृष्ठभूमि' ,
	'bad' : 'खराब' ,
	'badly' : 'बुरी तरह' ,
	'bag' : 'थैला' ,
	'bake' : 'सेंकना' ,
	'balance' : 'संतुलन' ,
	'ball' : 'गेंद' ,
	'band' : 'बैंड' ,
	'bank' : 'बैंक' ,
	'bar' : 'छड़' ,
	'barely' : 'मुश्किल से' ,
	'barrel' : 'बैरल' ,
	'barrier' : 'बैरियर' ,
	'base' : 'आधार' ,
	'baseball' : 'बेसबॉल' ,
	'basic' : 'बुनियादी' ,
	'basically' : 'मूल रूप से' ,
	'basis' : 'आधार' ,
	'basket' : 'टोकरी' ,
	'basketball' : 'बास्केटबाल' ,
	'bathroom' : 'स्नानघर' ,
	'battery' : 'बैटरी' ,
	'battle' : 'लड़ाई' ,
	'be' : 'होना' ,
	'beach' : 'सागरतट' ,
	'bean' : 'सेम' ,
	'bear' : 'भालू' ,
	'beat' : 'हराना' ,
	'beautiful' : 'सुंदर' ,
	'beauty' : 'सुंदरता' ,
	'because' : 'इसलिये' ,
	'become' : 'बनना' ,
	'bed' : 'बिस्तर' ,
	'bedroom' : 'शयनकक्ष' ,
	'beer' : 'बीयर' ,
	'before' : 'इससे पहले' ,
	'begin' : 'शुरू' ,
	'beginning' : 'शुरुआत' ,
	'behavior' : 'व्यवहार' ,
	'behind' : 'पीछे' ,
	'being' : 'हो रहा' ,
	'belief' : 'आस्था' ,
	'believe' : 'मानना' ,
	'bell' : 'घंटी' ,
	'belong' : 'संबंधित होना' ,
	'below' : 'नीचे' ,
	'belt' : 'बेल्ट' ,
	'bench' : 'बेंच' ,
	'bend' : 'झुकना' ,
	'beneath' : 'नीचे' ,
	'benefit' : 'फायदा' ,
	'beside' : 'पास' ,
	'besides' : 'के अतिरिक्त' ,
	'best' : 'श्रेष्ठ' ,
	'bet' : 'शर्त' ,
	'better' : 'बेहतर' ,
	'between' : 'के बीच' ,
	'beyond' : 'के परे' ,
	'Bible' : 'बाइबिल' ,
	'big' : 'बड़ा' ,
	'bike' : 'साइकिल' ,
	'bill' : 'विपत्र' ,
	'billion' : 'एक अरब' ,
	'bind' : 'बाँध' ,
	'biological' : 'जैविक' ,
	'bird' : 'चिड़िया' ,
	'birth' : 'जन्म' ,
	'birthday' : 'जन्मदिन' ,
	'bit' : 'अंश' ,
	'bite' : 'दांत से काटना' ,
	'black' : 'काला' ,
	'blade' : 'ब्लेड' ,
	'blame' : 'आरोप' ,
	'blanket' : 'कंबल' ,
	'blind' : 'अंधा' ,
	'block' : 'खंड मैथा' ,
	'blood' : 'रक्त' ,
	'blow' : 'फुंक मारा' ,
	'blue' : 'नीला' ,
	'board' : 'मंडल' ,
	'boat' : 'नाव' ,
	'body' : 'तन' ,
	'bomb' : 'बम' ,
	'bombing' : 'बम विस्फोट' ,
	'bond' : 'गहरा संबंध' ,
	'bone' : 'हड्डी' ,
	'book' : 'किताब' ,
	'boom' : 'बूम' ,
	'boot' : 'बीओओटी' ,
	'border' : 'बॉर्डर' ,
	'born' : 'जन्म' ,
	'borrow' : 'उधार' ,
	'boss' : 'मालिक' ,
	'both' : 'दोनों' ,
	'bother' : 'परेशानी' ,
	'bottle' : 'बोतल' ,
	'bottom' : 'तल' ,
	'boundary' : 'सीमा' ,
	'bowl' : 'कटोरा' ,
	'box' : 'डिब्बा' ,
	'boy' : 'लड़का' ,
	'boyfriend' : 'प्रेमी' ,
	'brain' : 'दिमाग' ,
	'branch' : 'डाली' ,
	'brand' : 'ब्रांड' ,
	'bread' : 'रोटी' ,
	'break' : 'तोड़ना' ,
	'breakfast' : 'सुबह का नाश्ता' ,
	'breast' : 'स्तन' ,
	'breath' : 'सांस' ,
	'breathe' : 'सांस लेना' ,
	'brick' : 'ईंट' ,
	'bridge' : 'पुल' ,
	'brief' : 'संक्षिप्त' ,
	'briefly' : 'संक्षिप्त' ,
	'bright' : 'चमकदार' ,
	'brilliant' : 'बहुत खूब' ,
	'bring' : 'लाओ' ,
	'British' : 'अंग्रेजों' ,
	'broad' : 'विस्तृत' ,
	'broken' : 'टूटा हुआ' ,
	'brother' : 'भाई' ,
	'brown' : 'भूरा' ,
	'brush' : 'ब्रश' ,
	'buck' : 'बक' ,
	'budget' : 'बजट' ,
	'build' : 'निर्माण' ,
	'building' : 'इमारत' ,
	'bullet' : 'गोली' ,
	'bunch' : 'झुंड' ,
	'burden' : 'बोझ' ,
	'burn' : 'जलाना' ,
	'bury' : 'गाड़' ,
	'bus' : 'बस' ,
	'business' : 'व्यापार' ,
	'busy' : 'व्यस्त' ,
	'but' : 'लेकिन' ,
	'butter' : 'मक्खन' ,
	'button' : 'बटन' ,
	'buy' : 'खरीदना' ,
	'buyer' : 'क्रेता' ,
	'by' : 'द्वारा' ,
	'cabin' : 'केबिन' ,
	'cabinet' : 'मंत्रिमंडल' ,
	'cable' : 'केबल' ,
	'cake' : 'केक' ,
	'calculate' : 'calculate' ,
	'call' : 'बुलाना' ,
	'camera' : 'कैमरा' ,
	'camp' : 'शिविर' ,
	'campaign' : 'अभियान' ,
	'campus' : 'कैंपस' ,
	'can' : 'कर सकते हैं' ,
	'Canadian' : 'कैनेडियन' ,
	'cancer' : 'कैंसर' ,
	'candidate' : 'उम्मीदवार' ,
	'cap' : 'टोपी' ,
	'capability' : 'क्षमता' ,
	'capable' : 'काबिल' ,
	'capacity' : 'क्षमता' ,
	'capital' : 'राजधानी' ,
	'captain' : 'कप्तान' ,
	'capture' : 'कब्जा' ,
	'car' : 'गाड़ी' ,
	'carbon' : 'कार्बन' ,
	'card' : 'कार्ड' ,
	'care' : 'देखभाल' ,
	'career' : 'आजीविका' ,
	'careful' : 'सावधान' ,
	'carefully' : 'सावधानी से' ,
	'carrier' : 'वाहक' ,
	'carry' : 'ढोना' ,
	'case' : 'मामला' ,
	'cash' : 'नकद' ,
	'cast' : 'ढालना' ,
	'cat' : 'बिल्ली' ,
	'catch' : 'पकड़' ,
	'category' : 'श्रेणी' ,
	'Catholic' : 'कैथोलिक' ,
	'cause' : 'वजह' ,
	'ceiling' : 'छत' ,
	'celebrate' : 'जश्न' ,
	'celebration' : 'उत्सव' ,
	'celebrity' : 'सेलिब्रिटी' ,
	'cell' : 'कक्ष' ,
	'center' : 'केंद्र' ,
	'central' : 'केंद्रीय' ,
	'century' : 'सदी' ,
	'CEO' : 'सीईओ' ,
	'ceremony' : 'समारोह' ,
	'certain' : 'कुछ' ,
	'certainly' : 'निश्चित रूप से' ,
	'chain' : 'जंजीर' ,
	'chair' : 'कुर्सी' ,
	'chairman' : 'अध्यक्ष' ,
	'challenge' : 'चुनौती' ,
	'chamber' : 'कक्ष' ,
	'champion' : 'चैंपियन' ,
	'championship' : 'चैंपियनशिप' ,
	'chance' : 'मोका' ,
	'change' : 'परिवर्तन' ,
	'changing' : 'बदलना' ,
	'channel' : 'चैनल' ,
	'chapter' : 'अध्याय' ,
	'character' : 'चरित्र' ,
	'characteristic' : 'विशेषता' ,
	'characterize' : 'विशेषताएँ' ,
	'charge' : 'चार्ज' ,
	'charity' : 'दान पुण्य' ,
	'chart' : 'चार्ट' ,
	'chase' : 'पीछा करना' ,
	'cheap' : 'सस्ता' ,
	'check' : 'जाँच' ,
	'cheek' : 'गाल' ,
	'cheese' : 'पनीर' ,
	'chef' : 'बावर्ची' ,
	'chemical' : 'रासायनिक' ,
	'chest' : 'छाती' ,
	'chicken' : 'मुर्गा' ,
	'chief' : 'अध्यक्ष' ,
	'child' : 'बच्चा' ,
	'childhood' : 'बचपन' ,
	'Chinese' : 'चीनी' ,
	'chip' : 'टुकड़ा' ,
	'chocolate' : 'चॉकलेट' ,
	'choice' : 'पसंद' ,
	'cholesterol' : 'कोलेस्ट्रॉल' ,
	'choose' : 'चुनें' ,
	'Christian' : 'ईसाई' ,
	'Christmas' : 'क्रिसमस' ,
	'church' : 'चर्च' ,
	'cigarette' : 'सिगरेट' ,
	'circle' : 'वृत्त' ,
	'circumstance' : 'परिस्थिति' ,
	'cite' : 'अदालत में तलब करना' ,
	'citizen' : 'नागरिक' ,
	'city' : 'शहर' ,
	'civil' : 'नागरिक' ,
	'civilian' : 'असैनिक' ,
	'claim' : 'दावा' ,
	'class' : 'कक्षा' ,
	'classic' : 'क्लासिक' ,
	'classroom' : 'कक्षा' ,
	'clean' : 'साफ' ,
	'clear' : 'स्पष्ट' ,
	'clearly' : 'स्पष्ट रूप से' ,
	'client' : 'ग्राहक' ,
	'climate' : 'जलवायु' ,
	'climb' : 'चढना' ,
	'clinic' : 'क्लिनिक' ,
	'clinical' : 'क्लीनिकल' ,
	'clock' : 'घड़ी' ,
	'close' : 'बंद करना' ,
	'closely' : 'निकट से' ,
	'closer' : 'करीब' ,
	'clothes' : 'कपड़े' ,
	'clothing' : 'कपड़े' ,
	'cloud' : 'बादल' ,
	'club' : 'क्लब' ,
	'clue' : 'संकेत' ,
	'cluster' : 'समूह' ,
	'coach' : 'कोच' ,
	'coal' : 'कोयला' ,
	'coalition' : 'गठबंधन' ,
	'coast' : 'कोस्ट' ,
	'coat' : 'कोट' ,
	'code' : 'कोड' ,
	'coffee' : 'कॉफ़ी' ,
	'cognitive' : 'संज्ञानात्मक' ,
	'cold' : 'सर्दी' ,
	'collapse' : 'ढहना' ,
	'colleague' : 'साथ काम करने वाला' ,
	'collect' : 'कलेक्ट' ,
	'collection' : 'संग्रह' ,
	'collective' : 'सामूहिक' ,
	'college' : 'महाविद्यालय' ,
	'colonial' : 'औपनिवेशिक' ,
	'color' : 'रंग' ,
	'column' : 'स्तंभ' ,
	'combination' : 'मेल' ,
	'combine' : 'जोड़ना' ,
	'come' : 'आइए' ,
	'comedy' : 'कॉमेडी' ,
	'comfort' : 'आराम' ,
	'comfortable' : 'आरामदायक' ,
	'command' : 'आदेश' ,
	'commander' : 'कमांडर' ,
	'comment' : 'टिप्पणी' ,
	'commercial' : 'व्यावसायिक' ,
	'commission' : 'आयोग' ,
	'commit' : 'प्रतिबद्ध' ,
	'commitment' : 'प्रतिबद्धता' ,
	'committee' : 'समिति' ,
	'common' : 'सामान्य' ,
	'communicate' : 'संवाद' ,
	'communication' : 'संचार' ,
	'community' : 'समुदाय' ,
	'company' : 'कंपनी' ,
	'compare' : 'तुलना करना' ,
	'comparison' : 'तुलना' ,
	'compete' : 'प्रतिस्पर्धा' ,
	'competition' : 'मुकाबला' ,
	'competitive' : 'प्रतियोगी' ,
	'competitor' : 'प्रतियोगी' ,
	'complain' : 'शिकायत' ,
	'complaint' : 'शिकायत' ,
	'complete' : 'पूर्ण' ,
	'completely' : 'पूरी तरह' ,
	'complex' : 'जटिल' ,
	'complicated' : 'जटिल' ,
	'component' : 'अवयव' ,
	'compose' : 'लिखें' ,
	'composition' : 'संयोजन' ,
	'comprehensive' : 'व्यापक' ,
	'computer' : 'संगणक' ,
	'concentrate' : 'ध्यान केंद्रित करना' ,
	'concentration' : 'एकाग्रता' ,
	'concept' : 'संकल्पना' ,
	'concern' : 'चिंता' ,
	'concerned' : 'चिंतित' ,
	'concert' : 'कंसर्ट' ,
	'conclude' : 'निष्कर्ष निकालना' ,
	'conclusion' : 'निष्कर्ष' ,
	'concrete' : 'ठोस' ,
	'condition' : 'स्थिति' ,
	'conduct' : 'आचरण' ,
	'conference' : 'सम्मेलन' ,
	'confidence' : 'आत्मविश्वास' ,
	'confident' : 'विश्वास है' ,
	'confirm' : 'पुष्टि करना' ,
	'conflict' : 'टकराव' ,
	'confront' : 'सामना होना' ,
	'confusion' : 'उलझन' ,
	'Congress' : 'कांग्रेस' ,
	'congressional' : 'कांग्रेस' ,
	'connect' : 'जुडिये' ,
	'connection' : 'संबंध' ,
	'consciousness' : 'चेतना' ,
	'consensus' : 'आम सहमति' ,
	'consequence' : 'परिणाम' ,
	'conservative' : 'अपरिवर्तनवादी' ,
	'consider' : 'विचार करना' ,
	'considerable' : 'विचारणीय' ,
	'consideration' : 'सोच - विचार' ,
	'consist' : 'बनावट' ,
	'consistent' : 'एक जैसा' ,
	'constant' : 'स्थिर' ,
	'constantly' : 'निरंतर' ,
	'constitute' : 'गठित करना' ,
	'constitutional' : 'संवैधानिक' ,
	'construct' : 'निर्माण' ,
	'construction' : 'निर्माण' ,
	'consultant' : 'सलाहकार' ,
	'consume' : 'उपभोग करना' ,
	'consumer' : 'उपभोक्ता' ,
	'consumption' : 'उपभोग' ,
	'contact' : 'संपर्क' ,
	'contain' : 'शामिल होना' ,
	'container' : 'पात्र' ,
	'contemporary' : 'समकालीन' ,
	'content' : 'विषय' ,
	'contest' : 'प्रतियोगिता' ,
	'context' : 'संदर्भ' ,
	'continue' : 'जारी रखें' ,
	'continued' : 'निरंतर' ,
	'contract' : 'अनुबंध' ,
	'contrast' : 'अंतर' ,
	'contribute' : 'योगदान' ,
	'contribution' : 'योगदान' ,
	'control' : 'नियंत्रण' ,
	'controversial' : 'विवादास्पद' ,
	'controversy' : 'विवाद' ,
	'convention' : 'सम्मेलन' ,
	'conventional' : 'पारंपरिक' ,
	'conversation' : 'बातचीत' ,
	'convert' : 'धर्मांतरित' ,
	'conviction' : 'दोषसिद्धि' ,
	'convince' : 'मनवाना' ,
	'cook' : 'रसोइया' ,
	'cookie' : 'कुकी' ,
	'cooking' : 'खाना बनाना' ,
	'cool' : 'ठंडा' ,
	'cooperation' : 'सहयोग' ,
	'cop' : 'पुलिस' ,
	'cope' : 'सामना' ,
	'copy' : 'प्रतिलिपि' ,
	'core' : 'सार' ,
	'corn' : 'मक्का' ,
	'corner' : 'कोने' ,
	'corporate' : 'निगमित' ,
	'corporation' : 'निगम' ,
	'correct' : 'सही' ,
	'correspondent' : 'संवाददाता' ,
	'cost' : 'कीमत' ,
	'cotton' : 'कपास' ,
	'couch' : 'सोफ़ा' ,
	'could' : 'सकता है' ,
	'council' : 'परिषद' ,
	'counselor' : 'काउंसलर' ,
	'count' : 'गिनती' ,
	'counter' : 'काउंटर' ,
	'country' : 'देश' ,
	'county' : 'काउंटी' ,
	'couple' : 'जोड़ा' ,
	'courage' : 'साहस' ,
	'course' : 'अवधि' ,
	'court' : 'कोर्ट' ,
	'cousin' : 'चचेरा भाई' ,
	'cover' : 'आवरण' ,
	'coverage' : 'कवरेज' ,
	'cow' : 'गाय' ,
	'crack' : 'दरार' ,
	'craft' : 'क्राफ्ट' ,
	'crash' : 'दुर्घटना' ,
	'crazy' : 'पागल' ,
	'cream' : 'मलाई' ,
	'create' : 'सृजन करना' ,
	'creation' : 'निर्माण' ,
	'creative' : 'रचनात्मक' ,
	'creature' : 'जंतु' ,
	'credit' : 'श्रेय' ,
	'crew' : 'कर्मी दल' ,
	'crime' : 'अपराध' ,
	'criminal' : 'आपराधिक' ,
	'crisis' : 'संकट' ,
	'criteria' : 'मानदंड' ,
	'critic' : 'समीक्षक' ,
	'critical' : 'नाजुक' ,
	'criticism' : 'आलोचना' ,
	'criticize' : 'आलोचना' ,
	'crop' : 'काटना' ,
	'cross' : 'पार करना' ,
	'crowd' : 'जन सैलाब' ,
	'crucial' : 'महत्वपूर्ण' ,
	'cry' : 'रोना' ,
	'cultural' : 'सांस्कृतिक' ,
	'culture' : 'संस्कृति' ,
	'cup' : 'कप' ,
	'curious' : 'जिज्ञासु' ,
	'current' : 'वर्तमान' ,
	'currently' : 'वर्तमान में' ,
	'curriculum' : 'पाठ्यक्रम' ,
	'custom' : 'रीति' ,
	'customer' : 'ग्राहक' ,
	'cut' : 'कट गया' ,
	'cycle' : 'चक्र' ,
	'dad' : 'पिता' ,
	'daily' : 'रोज' ,
	'damage' : 'क्षति' ,
	'dance' : 'नृत्य' ,
	'danger' : 'खतरा' ,
	'dangerous' : 'खतरनाक' ,
	'dare' : 'हिम्मत' ,
	'dark' : 'अंधेरा' ,
	'darkness' : 'अंधेरा' ,
	'data' : 'आंकड़े' ,
	'date' : 'दिनांक' ,
	'daughter' : 'बेटी' ,
	'day' : 'दिन' ,
	'dead' : 'मृत' ,
	'deal' : 'सौदा' ,
	'dealer' : 'विक्रेता' ,
	'dear' : 'प्रिय' ,
	'death' : 'मौत' ,
	'debate' : 'बहस' ,
	'debt' : 'कर्ज' ,
	'decade' : 'दशक' ,
	'decide' : 'निर्णय करना' ,
	'decision' : 'फैसला' ,
	'deck' : 'डेक' ,
	'declare' : 'घोषित' ,
	'decline' : 'पतन' ,
	'decrease' : 'कमी' ,
	'deep' : 'गहरा' ,
	'deeply' : 'गहरा' ,
	'deer' : 'मृग' ,
	'defeat' : 'परास्त करना' ,
	'defend' : 'रक्षा करना' ,
	'defendant' : 'प्रतिवादी' ,
	'defense' : 'रक्षा' ,
	'defensive' : 'बचाव' ,
	'deficit' : 'घाटा' ,
	'define' : 'परिभाषित करें' ,
	'definitely' : 'निश्चित रूप से' ,
	'definition' : 'परिभाषा' ,
	'degree' : 'डिग्री' ,
	'delay' : 'विलंब' ,
	'deliver' : 'उद्धार' ,
	'delivery' : 'वितरण' ,
	'demand' : 'मांग' ,
	'democracy' : 'जनतंत्र' ,
	'Democrat' : 'प्रजातंत्रवादी' ,
	'democratic' : 'लोकतांत्रिक' ,
	'demonstrate' : 'प्रदर्शन करना' ,
	'demonstration' : 'प्रदर्शन' ,
	'deny' : 'मना' ,
	'department' : 'विभाग' ,
	'depend' : 'निर्भर' ,
	'dependent' : 'आश्रित' ,
	'depending' : 'निर्भर करता है' ,
	'depict' : 'चित्रित' ,
	'depression' : 'डिप्रेशन' ,
	'depth' : 'गहराई' ,
	'deputy' : 'डिप्टी' ,
	'derive' : 'निकाले जाते हैं' ,
	'describe' : 'वर्णन करना' ,
	'description' : 'विवरण' ,
	'desert' : 'रेगिस्तान' ,
	'deserve' : 'योग्य होना' ,
	'design' : 'डिजाईन' ,
	'designer' : 'डिजाइनर' ,
	'desire' : 'मंशा' ,
	'desk' : 'डेस्क' ,
	'desperate' : 'बेकरार' ,
	'despite' : 'इसके बावजूद' ,
	'destroy' : 'नष्ट करना' ,
	'destruction' : 'विनाश' ,
	'detail' : 'विस्तार' ,
	'detailed' : 'विस्तृत' ,
	'detect' : 'पता लगाना' ,
	'determine' : 'ठानना' ,
	'develop' : 'विकसित करना' ,
	'developing' : 'विकसित होना' ,
	'development' : 'विकास' ,
	'device' : 'युक्ति' ,
	'devote' : 'समर्पित' ,
	'dialogue' : 'वार्ता' ,
	'diet' : 'आहार' ,
	'differ' : 'अलग होना' ,
	'difference' : 'अंतर' ,
	'different' : 'विभिन्न' ,
	'differently' : 'अलग ढंग से' ,
	'difficult' : 'कठिन' ,
	'difficulty' : 'कठिनाई' ,
	'digital' : 'डिजिटल' ,
	'dimension' : 'आयाम' ,
	'dining' : 'भोजन' ,
	'dinner' : 'रात का खाना' ,
	'direct' : 'सीधे' ,
	'direction' : 'दिशा' ,
	'directly' : 'सीधे' ,
	'director' : 'निर्देशक' ,
	'dirt' : 'गंदगी' ,
	'dirty' : 'गंदा' ,
	'disability' : 'विकलांगता' ,
	'disagree' : 'असहमत' ,
	'disappear' : 'गायब होना' ,
	'disaster' : 'आपदा' ,
	'discipline' : 'अनुशासन' ,
	'discourse' : 'प्रवचन' ,
	'discover' : 'डिस्कवर' ,
	'discovery' : 'खोज' ,
	'discrimination' : 'भेदभाव' ,
	'discuss' : 'चर्चा करें' ,
	'discussion' : 'विचार - विमर्श' ,
	'disease' : 'रोग' ,
	'dish' : 'थाली' ,
	'dismiss' : 'खारिज' ,
	'disorder' : 'विकार' ,
	'display' : 'प्रदर्शन' ,
	'dispute' : 'विवाद' ,
	'distance' : 'दूरी' ,
	'distant' : 'दूरस्थ' ,
	'distinct' : 'अलग' ,
	'distinction' : 'भेद' ,
	'distinguish' : 'अंतर करना' ,
	'distribute' : 'वितरित करना' ,
	'distribution' : 'वितरण' ,
	'district' : 'जिला' ,
	'diverse' : 'विविध' ,
	'diversity' : 'विविधता' ,
	'divide' : 'विभाजन' ,
	'division' : 'विभाजन' ,
	'divorce' : 'तलाक' ,
	'DNA' : 'डीएनए' ,
	'do' : 'करना' ,
	'doctor' : 'चिकित्सक' ,
	'document' : 'डाक्यूमेंट' ,
	'dog' : 'कुत्ता' ,
	'domestic' : 'घरेलू' ,
	'dominant' : 'प्रमुख' ,
	'dominate' : 'हावी होना' ,
	'door' : 'द्वार' ,
	'double' : 'दोहरा' ,
	'doubt' : 'शक' ,
	'down' : 'नीचे' ,
	'downtown' : 'शहर' ,
	'dozen' : 'दर्जन' ,
	'draft' : 'प्रारूप' ,
	'drag' : 'खींचना' ,
	'drama' : 'नाटक' ,
	'dramatic' : 'नाटकीय' ,
	'dramatically' : 'नाटकीय रूप से' ,
	'draw' : 'खींचना' ,
	'drawing' : 'चित्रकारी' ,
	'dream' : 'सपना' ,
	'dress' : 'पोशाक' ,
	'drink' : 'पीना' ,
	'drive' : 'चलाना' ,
	'driver' : 'चालक' ,
	'drop' : 'बूंद' ,
	'drug' : 'दवाई' ,
	'dry' : 'सूखा' ,
	'due' : 'देय' ,
	'during' : 'दौरान' ,
	'dust' : 'धूल' ,
	'duty' : 'कर्तव्य' ,
	'each' : 'प्रत्येक' ,
	'eager' : 'आतुर' ,
	'ear' : 'कान' ,
	'early' : 'शीघ्र' ,
	'earn' : 'कमाना' ,
	'earnings' : 'आय' ,
	'earth' : 'धरती' ,
	'ease' : 'आराम' ,
	'easily' : 'सरलता' ,
	'east' : 'पूर्व' ,
	'eastern' : 'पूर्व का' ,
	'easy' : 'आसान' ,
	'eat' : 'खाना खा लो' ,
	'economic' : 'आर्थिक' ,
	'economics' : 'अर्थशास्त्र' ,
	'economist' : 'अर्थशास्त्री' ,
	'economy' : 'अर्थव्यवस्था' ,
	'edge' : 'किनारा' ,
	'edition' : 'संस्करण' ,
	'editor' : 'संपादक' ,
	'educate' : 'शिक्षित' ,
	'education' : 'शिक्षा' ,
	'educational' : 'शिक्षात्मक' ,
	'educator' : 'शिक्षक' ,
	'effect' : 'प्रभाव' ,
	'effective' : 'प्रभावी' ,
	'effectively' : 'प्रभावी रूप से' ,
	'efficiency' : 'क्षमता' ,
	'efficient' : 'कुशल' ,
	'effort' : 'प्रयास' ,
	'egg' : 'अंडा' ,
	'eight' : 'आठ' ,
	'either' : 'दोनों में से एक' ,
	'elderly' : 'बुज़ुर्ग' ,
	'elect' : 'इलेक्ट्रोनिक' ,
	'election' : 'चुनाव' ,
	'electric' : 'बिजली' ,
	'electricity' : 'बिजली' ,
	'electronic' : 'इलेक्ट्रोनिक' ,
	'element' : 'तत्त्व' ,
	'elementary' : 'प्राथमिक' ,
	'eliminate' : 'हटाना' ,
	'elite' : 'अभिजात वर्ग' ,
	'else' : 'अन्य' ,
	'elsewhere' : 'कहीं' ,
	'embrace' : 'अंगीकार करना' ,
	'emerge' : 'उभरना' ,
	'emergency' : 'आपातकालीन' ,
	'emission' : 'उत्सर्जन' ,
	'emotion' : 'भावना' ,
	'emotional' : 'भावुक' ,
	'emphasis' : 'ज़ोर' ,
	'emphasize' : 'ज़ोर देना' ,
	'employ' : 'काम' ,
	'employee' : 'कर्मचारी' ,
	'employer' : 'नियोक्ता' ,
	'employment' : 'रोज़गार' ,
	'empty' : 'खाली' ,
	'enable' : 'सक्षम' ,
	'encounter' : 'मुठभेड़' ,
	'encourage' : 'प्रोत्साहित करना' ,
	'end' : 'समाप्त' ,
	'enemy' : 'दुश्मन' ,
	'energy' : 'ऊर्जा' ,
	'enforcement' : 'प्रवर्तन' ,
	'engage' : 'काम पर लगाना' ,
	'engine' : 'यन्त्र' ,
	'engineer' : 'इंजीनियर' ,
	'engineering' : 'अभियांत्रिकी' ,
	'English' : 'अंग्रेज़ी' ,
	'enhance' : 'सुधारना' ,
	'enjoy' : 'का आनंद लें' ,
	'enormous' : 'विशाल' ,
	'enough' : 'पर्याप्त' ,
	'ensure' : 'सुनिश्चित करना' ,
	'enter' : 'दर्ज' ,
	'enterprise' : 'उद्यम' ,
	'entertainment' : 'मनोरंजन' ,
	'entire' : 'संपूर्ण' ,
	'entirely' : 'पूरी तरह से' ,
	'entrance' : 'प्रवेश' ,
	'entry' : 'प्रवेश' ,
	'environment' : 'वातावरण' ,
	'environmental' : 'पर्यावरण' ,
	'episode' : 'प्रकरण' ,
	'equal' : 'बराबरी का' ,
	'equally' : 'समान रूप से' ,
	'equipment' : 'उपकरण' ,
	'era' : 'युग' ,
	'error' : 'त्रुटि' ,
	'escape' : 'पलायन' ,
	'especially' : 'विशेष रूप से' ,
	'essay' : 'निबंध' ,
	'essential' : 'आवश्यक' ,
	'essentially' : 'अनिवार्य रूप से' ,
	'establish' : 'स्थापित करना' ,
	'establishment' : 'स्थापना' ,
	'estate' : 'जायदाद' ,
	'estimate' : 'आकलन' ,
	'etc' : 'आदि' ,
	'ethics' : 'आचार विचार' ,
	'ethnic' : 'संजाति विषयक' ,
	'European' : 'यूरोपीय' ,
	'evaluate' : 'मूल्यांकन करना' ,
	'evaluation' : 'मूल्यांकन' ,
	'even' : 'यहाँ तक की' ,
	'evening' : 'शाम' ,
	'event' : 'प्रतिस्पर्धा' ,
	'eventually' : 'अंततः' ,
	'ever' : 'कभी' ,
	'every' : 'हर एक' ,
	'everybody' : 'हर' ,
	'everyday' : 'हर दिन' ,
	'everyone' : 'हर कोई' ,
	'everything' : 'हर चीज़' ,
	'everywhere' : 'हर जगह' ,
	'evidence' : 'सबूत' ,
	'evolution' : 'क्रमागत उन्नति' ,
	'evolve' : 'विकसित करना' ,
	'exact' : 'सटीक' ,
	'exactly' : 'बिल्कुल सही' ,
	'examination' : 'इंतिहान' ,
	'examine' : 'की जांच' ,
	'example' : 'उदाहरण' ,
	'exceed' : 'पार करना' ,
	'excellent' : 'अति उत्कृष्ट' ,
	'except' : 'के अलावा' ,
	'exception' : 'अपवाद' ,
	'exchange' : 'लेन देन' ,
	'exciting' : 'उत्तेजित करनेवाला' ,
	'executive' : 'कार्यपालक' ,
	'exercise' : 'व्यायाम' ,
	'exhibit' : 'प्रदर्शन' ,
	'exhibition' : 'प्रदर्शनी' ,
	'exist' : 'मौजूद' ,
	'existence' : 'अस्तित्व' ,
	'existing' : 'मौजूदा' ,
	'expand' : 'विस्तार' ,
	'expansion' : 'विस्तार' ,
	'expect' : 'अपेक्षा करना' ,
	'expectation' : 'अपेक्षा' ,
	'expense' : 'व्यय' ,
	'expensive' : 'महंगा' ,
	'experience' : 'अनुभव' ,
	'experiment' : 'प्रयोग' ,
	'expert' : 'विशेषज्ञ' ,
	'explain' : 'समझाना' ,
	'explanation' : 'व्याख्या' ,
	'explode' : 'विस्फोट' ,
	'explore' : 'अन्वेषण करना' ,
	'explosion' : 'विस्फोट' ,
	'expose' : 'अनावृत करना' ,
	'exposure' : 'अनावरण' ,
	'express' : 'व्यक्त करना' ,
	'expression' : 'अभिव्यक्ति' ,
	'extend' : 'विस्तार' ,
	'extension' : 'विस्तार' ,
	'extensive' : 'बहुत बड़ा' ,
	'extent' : 'क्षेत्र' ,
	'external' : 'बाहरी' ,
	'extra' : 'अतिरिक्त' ,
	'extraordinary' : 'असाधारण' ,
	'extreme' : 'चरम' ,
	'extremely' : 'अत्यंत' ,
	'eye' : 'आंख' ,
	'fabric' : 'कपड़ा' ,
	'face' : 'चेहरा' ,
	'facility' : 'सुविधा' ,
	'fact' : 'तथ्य' ,
	'factor' : 'फ़ैक्टर' ,
	'factory' : 'फ़ैक्टरी' ,
	'faculty' : 'संकाय' ,
	'fade' : 'मुरझाना' ,
	'fail' : 'विफल' ,
	'failure' : 'असफलता' ,
	'fair' : 'निष्पक्ष' ,
	'fairly' : 'काफी' ,
	'faith' : 'आस्था' ,
	'fall' : 'गिरना' ,
	'false' : 'असत्य' ,
	'familiar' : 'परिचित' ,
	'family' : 'परिवार' ,
	'famous' : 'प्रसिद्ध' ,
	'fan' : 'पंखा' ,
	'fantasy' : 'कल्पना' ,
	'far' : 'दूर' ,
	'farm' : 'खेत' ,
	'farmer' : 'किसान' ,
	'fashion' : 'फैशन' ,
	'fast' : 'तेज़' ,
	'fat' : 'मोटा' ,
	'fate' : 'भाग्य' ,
	'father' : 'पिता' ,
	'fault' : 'दोष' ,
	'favor' : 'एहसान' ,
	'favorite' : 'पसंदीदा' ,
	'fear' : 'डर' ,
	'feature' : 'विशेषता' ,
	'federal' : 'संघीय' ,
	'fee' : 'शुल्क' ,
	'feed' : 'चारा' ,
	'feel' : 'बोध' ,
	'feeling' : 'भावना' ,
	'fellow' : 'साथी' ,
	'female' : 'महिला' ,
	'fence' : 'बाड़' ,
	'few' : 'कुछ' ,
	'fewer' : 'कम' ,
	'fiber' : 'रेशा' ,
	'fiction' : 'उपन्यास' ,
	'field' : 'खेत' ,
	'fifteen' : 'पंद्रह' ,
	'fifth' : 'पांचवां' ,
	'fifty' : 'पचास' ,
	'fight' : 'लड़ाई' ,
	'fighter' : 'योद्धा' ,
	'fighting' : 'मार पिटाई' ,
	'figure' : 'आकृति' ,
	'file' : 'फ़ाइल' ,
	'fill' : 'भरना' ,
	'film' : 'फ़िल्म' ,
	'final' : 'अंतिम' ,
	'finally' : 'आखिरकार' ,
	'finance' : 'वित्त' ,
	'financial' : 'वित्तीय' ,
	'find' : 'पाना' ,
	'finding' : 'खोज' ,
	'fine' : 'ठीक' ,
	'finger' : 'उंगली' ,
	'finish' : 'समाप्त' ,
	'fire' : 'आग' ,
	'firm' : 'दृढ़' ,
	'first' : 'सबसे पहले' ,
	'fish' : 'मछली' ,
	'fishing' : 'मछली पकड़ने' ,
	'fit' : 'फिट' ,
	'fitness' : 'स्वास्थ्य' ,
	'five' : 'पांच' ,
	'fix' : 'ठीक कर' ,
	'flag' : 'झंडा' ,
	'flame' : 'ज्योति' ,
	'flat' : 'समतल' ,
	'flavor' : 'स्वाद' ,
	'flee' : 'भागना' ,
	'flesh' : 'मोटापा' ,
	'flight' : 'उड़ान' ,
	'float' : 'पानी पर तैरना' ,
	'floor' : 'मंज़िल' ,
	'flow' : 'बहे' ,
	'flower' : 'फूल' ,
	'fly' : 'उड़ना' ,
	'focus' : 'केंद्र' ,
	'folk' : 'लोक' ,
	'follow' : 'पालन ​​करना' ,
	'following' : 'अगले' ,
	'food' : 'खाना' ,
	'foot' : 'पैर' ,
	'football' : 'फ़ुटबॉल' ,
	'for' : 'के लिये' ,
	'force' : 'बल' ,
	'foreign' : 'विदेश' ,
	'forest' : 'वन' ,
	'forever' : 'हमेशा के लिए' ,
	'forget' : 'भूल जाओ' ,
	'form' : 'प्रपत्र' ,
	'formal' : 'औपचारिक' ,
	'formation' : 'गठन' ,
	'former' : 'भूतपूर्व' ,
	'formula' : 'सूत्र' ,
	'forth' : 'आगे' ,
	'fortune' : 'भाग्य' ,
	'forward' : 'आगे' ,
	'found' : 'मिला' ,
	'foundation' : 'नींव' ,
	'founder' : 'संस्थापक' ,
	'four' : 'चार' ,
	'fourth' : 'चौथी' ,
	'frame' : 'ढांचा' ,
	'framework' : 'ढांचा' ,
	'free' : 'नि: शुल्क' ,
	'freedom' : 'आजादी' ,
	'freeze' : 'फ्रीज' ,
	'French' : 'फ्रेंच' ,
	'frequency' : 'आवृत्ति' ,
	'frequent' : 'बारंबार' ,
	'frequently' : 'बार बार' ,
	'fresh' : 'ताज़ा' ,
	'friend' : 'दोस्त' ,
	'friendly' : 'अनुकूल' ,
	'friendship' : 'मित्रता' ,
	'from' : 'से' ,
	'front' : 'सामने' ,
	'fruit' : 'फल' ,
	'frustration' : 'निराशा' ,
	'fuel' : 'ईंधन' ,
	'full' : 'भरा हुआ' ,
	'fully' : 'पूरी तरह से' ,
	'fun' : 'मज़ा' ,
	'function' : 'समारोह' ,
	'fund' : 'निधि' ,
	'fundamental' : 'मौलिक' ,
	'funding' : 'वित्त पोषण' ,
	'funeral' : 'अंतिम संस्कार' ,
	'funny' : 'मजेदार' ,
	'furniture' : 'फर्नीचर' ,
	'furthermore' : 'और भी' ,
	'future' : 'भविष्य' ,
	'gain' : 'बढ़त' ,
	'galaxy' : 'आकाशगंगा' ,
	'gallery' : 'गेलरी' ,
	'game' : 'खेल' ,
	'gang' : 'गिरोह' ,
	'gap' : 'अन्तर' ,
	'garage' : 'गेराज' ,
	'garden' : 'बगीचा' ,
	'garlic' : 'लहसुन' ,
	'gas' : 'गैस' ,
	'gate' : 'द्वार' ,
	'gather' : 'इकट्ठा करना' ,
	'gay' : 'समलैंगिक' ,
	'gaze' : 'निगाहें' ,
	'gear' : 'गियर' ,
	'gender' : 'लिंग' ,
	'gene' : 'जीन' ,
	'general' : 'आम' ,
	'generally' : 'आम तौर पर' ,
	'generate' : 'उत्पन्न' ,
	'generation' : 'पीढ़ी' ,
	'genetic' : 'जेनेटिक' ,
	'gentleman' : 'सज्जन' ,
	'gently' : 'धीरे' ,
	'German' : 'जर्मन' ,
	'gesture' : 'हाव - भाव' ,
	'get' : 'प्राप्त' ,
	'ghost' : 'भूत' ,
	'giant' : 'विशाल' ,
	'gift' : 'उपहार' ,
	'gifted' : 'प्रतिभाशाली' ,
	'girl' : 'लड़की' ,
	'girlfriend' : 'प्रेमिका' ,
	'give' : 'देना' ,
	'given' : 'दिया गया' ,
	'glad' : 'प्रसन्न' ,
	'glance' : 'झलक' ,
	'glass' : 'कांच' ,
	'global' : 'वैश्विक' ,
	'glove' : 'दस्ताना' ,
	'go' : 'जाओ' ,
	'goal' : 'लक्ष्य' ,
	'God' : 'भगवान' ,
	'gold' : 'सोना' ,
	'golden' : 'स्वर्ण' ,
	'golf' : 'गोल्फ़' ,
	'good' : 'अच्छा' ,
	'government' : 'सरकार' ,
	'governor' : 'राज्यपाल' ,
	'grab' : 'लपकना' ,
	'grade' : 'ग्रेड' ,
	'gradually' : 'धीरे - धीरे' ,
	'graduate' : 'स्नातक' ,
	'grain' : 'अनाज' ,
	'grand' : 'बड़ा' ,
	'grandfather' : 'दादा' ,
	'grandmother' : 'दादी मा' ,
	'grant' : 'अनुदान' ,
	'grass' : 'घास' ,
	'grave' : 'गंभीर' ,
	'gray' : 'धूसर' ,
	'great' : 'महान' ,
	'greatest' : 'महानतम' ,
	'green' : 'हरा' ,
	'grocery' : 'किराना' ,
	'ground' : 'ज़मीन' ,
	'group' : 'समूह' ,
	'grow' : 'बढ़ना' ,
	'growing' : 'बढ़ रही है' ,
	'growth' : 'विकास' ,
	'guarantee' : 'गारंटी' ,
	'guard' : 'रक्षक' ,
	'guess' : 'अनुमान' ,
	'guest' : 'अतिथि' ,
	'guide' : 'मार्गदर्शक' ,
	'guideline' : 'दिशानिर्देश' ,
	'guilty' : 'दोषी' ,
	'gun' : 'बंदूक' ,
	'guy' : 'लोग' ,
	'habit' : 'आदत' ,
	'habitat' : 'प्राकृतिक वास' ,
	'hair' : 'केश' ,
	'half' : 'आधा' ,
	'hall' : 'हॉल' ,
	'hand' : 'हाथ' ,
	'handful' : 'मुट्ठी' ,
	'handle' : 'हैंडल' ,
	'hang' : 'टांगना' ,
	'happen' : 'होना' ,
	'happy' : 'प्रसन्न' ,
	'hard' : 'मुश्किल' ,
	'hardly' : 'मुश्किल से' ,
	'hat' : 'टोपी' ,
	'hate' : 'घृणा' ,
	'have' : 'पास होना' ,
	'he' : 'वह' ,
	'head' : 'सिर' ,
	'headline' : 'शीर्षक' ,
	'headquarters' : 'मुख्यालय' ,
	'health' : 'स्वास्थ्य' ,
	'healthy' : 'स्वस्थ' ,
	'hear' : 'सुनो' ,
	'hearing' : 'सुनवाई' ,
	'heart' : 'दिल' ,
	'heat' : 'गर्मी' ,
	'heaven' : 'स्वर्ग' ,
	'heavily' : 'भारी' ,
	'heavy' : 'अधिक वज़नदार' ,
	'heel' : 'एड़ी' ,
	'height' : 'ऊंचाई' ,
	'helicopter' : 'हेलीकॉप्टर' ,
	'hell' : 'नरक' ,
	'hello' : 'नमस्ते' ,
	'help' : 'मदद' ,
	'helpful' : 'उपयोगी' ,
	'her' : 'उसकी' ,
	'here' : 'यहां' ,
	'heritage' : 'विरासत' ,
	'hero' : 'नायक' ,
	'herself' : 'स्वयं' ,
	'hey' : 'अरे' ,
	'hi' : 'नमस्ते' ,
	'hide' : 'छिपाना' ,
	'high' : 'उच्च' ,
	'highlight' : 'मुख्य आकर्षण' ,
	'highly' : 'अत्यधिक' ,
	'highway' : 'हाइवे' ,
	'hill' : 'पहाड़ी' ,
	'him' : 'उसे' ,
	'himself' : 'वह स्वयं' ,
	'hip' : 'कूल्हा' ,
	'hire' : 'किराये' ,
	'his' : 'उनके' ,
	'historian' : 'इतिहासकार' ,
	'historic' : 'ऐतिहासिक' ,
	'historical' : 'ऐतिहासिक' ,
	'history' : 'इतिहास' ,
	'hit' : 'मारो' ,
	'hold' : 'पकड़' ,
	'hole' : 'छेद' ,
	'holiday' : 'छुट्टी का दिन' ,
	'holy' : 'पवित्र' ,
	'home' : 'घर' ,
	'homeless' : 'बेघर' ,
	'honest' : 'ईमानदार' ,
	'honey' : 'शहद' ,
	'honor' : 'सम्मान' ,
	'hope' : 'आशा' ,
	'horizon' : 'क्षितिज' ,
	'horror' : 'डरावनी' ,
	'horse' : 'घोड़ा' ,
	'hospital' : 'अस्पताल' ,
	'host' : 'मेज़बान' ,
	'hot' : 'गरम' ,
	'hotel' : 'होटल' ,
	'hour' : 'घंटा' ,
	'house' : 'मकान' ,
	'household' : 'गृहस्थी' ,
	'housing' : 'आवास' ,
	'how' : 'कैसे' ,
	'however' : 'हालांकि' ,
	'huge' : 'विशाल' ,
	'human' : 'मानव' ,
	'humor' : 'हास्य' ,
	'hundred' : 'सौ' ,
	'hungry' : 'भूखा' ,
	'hunter' : 'शिकारी' ,
	'hunting' : 'शिकार करना' ,
	'hurt' : 'आहत' ,
	'husband' : 'पति' ,
	'hypothesis' : 'परिकल्पना' ,
	'I' : 'मैं' ,
	'ice' : 'बर्फ' ,
	'idea' : 'विचार' ,
	'ideal' : 'आदर्श' ,
	'identification' : 'पहचान' ,
	'identify' : 'पहचान लो' ,
	'identity' : 'पहचान' ,
	'ie' : 'अर्थात' ,
	'if' : 'अगर' ,
	'ignore' : 'नज़रअंदाज़ करना' ,
	'ill' : 'बीमार' ,
	'illegal' : 'अवैध' ,
	'illness' : 'बीमारी' ,
	'illustrate' : 'उदाहरण देकर स्पष्ट करना' ,
	'image' : 'छवि' ,
	'imagination' : 'कल्पना' ,
	'imagine' : 'कल्पना कीजिए' ,
	'immediate' : 'तुरंत' ,
	'immediately' : 'तुरंत' ,
	'immigrant' : 'आप्रवासी' ,
	'immigration' : 'अप्रवासन' ,
	'impact' : 'प्रभाव' ,
	'implement' : 'लागू' ,
	'implication' : 'निहितार्थ' ,
	'imply' : 'मतलब' ,
	'importance' : 'महत्त्व' ,
	'important' : 'जरूरी' ,
	'impose' : 'थोपना' ,
	'impossible' : 'असंभव' ,
	'impress' : 'छाप' ,
	'impression' : 'प्रभाव' ,
	'impressive' : 'प्रभावशाली' ,
	'improve' : 'सुधारें' ,
	'improvement' : 'सुधार की' ,
	'in' : 'में' ,
	'incentive' : 'प्रोत्साहन' ,
	'incident' : 'घटना' ,
	'include' : 'शामिल करना' ,
	'including' : 'समेत' ,
	'income' : 'आय' ,
	'incorporate' : 'शामिल' ,
	'increase' : 'बढ़ना' ,
	'increased' : 'बढ गय़े' ,
	'increasing' : 'की बढ़ती' ,
	'increasingly' : 'तेजी से' ,
	'incredible' : 'अविश्वसनीय' ,
	'indeed' : 'वास्तव में' ,
	'independence' : 'आजादी' ,
	'independent' : 'स्वतंत्र' ,
	'index' : 'अनुक्रमणिका' ,
	'Indian' : 'भारतीय' ,
	'indicate' : 'संकेत मिलता है' ,
	'indication' : 'संकेत' ,
	'individual' : 'व्यक्ति' ,
	'industrial' : 'औद्योगिक' ,
	'industry' : 'उद्योग' ,
	'infant' : 'शिशु' ,
	'infection' : 'संक्रमण' ,
	'inflation' : 'मुद्रास्फीति' ,
	'influence' : 'प्रभाव' ,
	'inform' : 'सूचित करना' ,
	'information' : 'जानकारी' ,
	'ingredient' : 'घटक' ,
	'initial' : 'प्रारंभिक' ,
	'initially' : 'शुरू में' ,
	'initiative' : 'पहल' ,
	'injury' : 'चोट' ,
	'inner' : 'भीतरी' ,
	'innocent' : 'मासूम' ,
	'inquiry' : 'जांच' ,
	'inside' : 'के भीतर' ,
	'insight' : 'अंतर्दृष्टि' ,
	'insist' : 'ज़ोर देना' ,
	'inspire' : 'प्रेरित करना' ,
	'install' : 'इंस्टॉल' ,
	'instance' : 'उदाहरण' ,
	'instead' : 'बजाय' ,
	'institution' : 'संस्थान' ,
	'institutional' : 'संस्थागत' ,
	'instruction' : 'अनुदेश' ,
	'instructor' : 'प्रशिक्षक' ,
	'instrument' : 'यंत्र' ,
	'insurance' : 'बीमा' ,
	'intellectual' : 'बौद्धिक' ,
	'intelligence' : 'बुद्धि' ,
	'intend' : 'इरादा करना' ,
	'intense' : 'तीव्र' ,
	'intensity' : 'तीव्रता' ,
	'intention' : 'इरादा' ,
	'interaction' : 'परस्पर क्रिया' ,
	'interest' : 'ब्याज' ,
	'interested' : 'इच्छुक' ,
	'interesting' : 'दिलचस्प' ,
	'internal' : 'अंदर का' ,
	'international' : 'अंतरराष्ट्रीय' ,
	'Internet' : 'इंटरनेट' ,
	'interpret' : 'व्याख्या' ,
	'interpretation' : 'व्याख्या' ,
	'intervention' : 'हस्तक्षेप' ,
	'interview' : 'साक्षात्कार' ,
	'into' : 'में' ,
	'introduce' : 'परिचय कराना' ,
	'introduction' : 'परिचय' ,
	'invasion' : 'आक्रमण' ,
	'invest' : 'निवेश' ,
	'investigate' : 'छान - बीन करना' ,
	'investigation' : 'जाँच पड़ताल' ,
	'investigator' : 'अन्वेषक' ,
	'investment' : 'निवेश' ,
	'investor' : 'इन्वेस्टर' ,
	'invite' : 'आमंत्रण' ,
	'involve' : 'शामिल' ,
	'involved' : 'शामिल' ,
	'involvement' : 'भागीदारी' ,
	'Iraqi' : 'इराक' ,
	'Irish' : 'आयरिश' ,
	'iron' : 'लोहा' ,
	'Islamic' : 'इस्लामी' ,
	'island' : 'द्वीप' ,
	'Israeli' : 'इजरायल' ,
	'issue' : 'मुद्दा' ,
	'it' : 'यह' ,
	'Italian' : 'इतालवी' ,
	'item' : 'मद' ,
	'its' : 'इसका' ,
	'itself' : 'अपने आप' ,
	'jacket' : 'जैकेट' ,
	'jail' : 'जेल' ,
	'Japanese' : 'जापानी' ,
	'jet' : 'जेट' ,
	'Jew' : 'यहूदी' ,
	'Jewish' : 'यहूदी' ,
	'job' : 'काम' ,
	'join' : 'में शामिल होने के' ,
	'joint' : 'संयुक्त' ,
	'joke' : 'मज़ाक' ,
	'journal' : 'पत्रिका' ,
	'journalist' : 'पत्रकार' ,
	'journey' : 'यात्रा' ,
	'joy' : 'हर्ष' ,
	'judge' : 'न्यायाधीश' ,
	'judgment' : 'प्रलय' ,
	'juice' : 'रस' ,
	'jump' : 'कूद' ,
	'junior' : 'कनिष्ठ' ,
	'jury' : 'पंचायत' ,
	'just' : 'अभी - अभी' ,
	'justice' : 'न्याय' ,
	'justify' : 'औचित्य साबित' ,
	'keep' : 'रखना' ,
	'key' : 'चाभी' ,
	'kick' : 'लात' ,
	'kid' : 'बच्चा' ,
	'kill' : 'मार' ,
	'killer' : 'हत्यारा' ,
	'killing' : 'हत्या' ,
	'kind' : 'दयालु' ,
	'king' : 'राजा' ,
	'kiss' : 'चुम्मा' ,
	'kitchen' : 'रसोईघर' ,
	'knee' : 'घुटना' ,
	'knife' : 'चाकू' ,
	'knock' : 'दस्तक' ,
	'know' : 'जानना' ,
	'knowledge' : 'ज्ञान' ,
	'lab' : 'प्रयोगशाला' ,
	'label' : 'लेबल' ,
	'labor' : 'श्रम' ,
	'laboratory' : 'प्रयोगशाला' ,
	'lack' : 'कमी' ,
	'lady' : 'महिला' ,
	'lake' : 'झील' ,
	'land' : 'भूमि' ,
	'landscape' : 'परिदृश्य' ,
	'language' : 'भाषा: हिन्दी' ,
	'lap' : 'गोद' ,
	'large' : 'बड़ा' ,
	'largely' : 'काफी हद तक' ,
	'last' : 'अंतिम' ,
	'late' : 'देर' ,
	'later' : 'बाद में' ,
	'Latin' : 'लैटिन' ,
	'latter' : 'बाद वाला' ,
	'laugh' : 'हसना' ,
	'launch' : 'प्रक्षेपण' ,
	'law' : 'कानून' ,
	'lawn' : 'लॉन' ,
	'lawsuit' : 'मुकदमा' ,
	'lawyer' : 'वकील' ,
	'lay' : 'धूल में मिलना' ,
	'layer' : 'परत' ,
	'lead' : 'प्रमुख' ,
	'leader' : 'नेता' ,
	'leadership' : 'नेतृत्व' ,
	'leading' : 'प्रमुख' ,
	'leaf' : 'पत्ता' ,
	'league' : 'संघ' ,
	'lean' : 'दुबला' ,
	'learn' : 'सीखना' ,
	'learning' : 'सीख रहा हूँ' ,
	'least' : 'कम से कम' ,
	'leather' : 'चमड़ा' ,
	'leave' : 'छुट्टी' ,
	'left' : 'बाएं' ,
	'leg' : 'टांग' ,
	'legacy' : 'विरासत' ,
	'legal' : 'कानूनी' ,
	'legend' : 'दंतकथा' ,
	'legislation' : 'विधान' ,
	'legitimate' : 'वैध' ,
	'lemon' : 'नींबू' ,
	'length' : 'लंबाई' ,
	'less' : 'कम' ,
	'lesson' : 'सबक' ,
	'let' : 'होने देना' ,
	'letter' : 'पत्र' ,
	'level' : 'स्तर' ,
	'liberal' : 'उदारवादी' ,
	'library' : 'पुस्तकालय' ,
	'license' : 'लाइसेंस' ,
	'lie' : 'झूठ' ,
	'life' : 'जीवन' ,
	'lifestyle' : 'बॉलीवुड' ,
	'lifetime' : 'जीवनभर' ,
	'lift' : 'उठाना' ,
	'light' : 'रोशनी' ,
	'like' : 'पसंद' ,
	'likely' : 'उपयुक्त' ,
	'limit' : 'सीमा' ,
	'limitation' : 'परिसीमन' ,
	'limited' : 'सीमित' ,
	'line' : 'रेखा' ,
	'link' : 'संपर्क' ,
	'lip' : 'ओंठ' ,
	'list' : 'सूची' ,
	'listen' : 'सुनना' ,
	'literally' : 'अक्षरशः' ,
	'literary' : 'साहित्यिक' ,
	'literature' : 'साहित्य' ,
	'little' : 'थोड़ा' ,
	'live' : 'लाइव' ,
	'living' : 'जीविका' ,
	'load' : 'भार' ,
	'loan' : 'ऋण' ,
	'local' : 'स्थानीय' ,
	'locate' : 'का पता लगाने' ,
	'location' : 'स्थान' ,
	'lock' : 'लॉक' ,
	'long' : 'लंबा' ,
	'long-term' : 'दीर्घकालिक' ,
	'look' : 'देखना' ,
	'loose' : 'ढीला' ,
	'lose' : 'खोना' ,
	'loss' : 'नुकसान' ,
	'lost' : 'खोया' ,
	'lot' : 'बहुत' ,
	'lots' : 'बहुत सारे' ,
	'loud' : 'जोर' ,
	'love' : 'प्यार' ,
	'lovely' : 'सुंदर' ,
	'lover' : 'प्रेम करनेवाला' ,
	'low' : 'कम' ,
	'lower' : 'कम' ,
	'luck' : 'भाग्य' ,
	'lucky' : 'भाग्यशाली' ,
	'lunch' : 'दोपहर का भोजन' ,
	'lung' : 'फेफड़ा' ,
	'machine' : 'मशीन' ,
	'mad' : 'पागल' ,
	'magazine' : 'पत्रिका' ,
	'mail' : 'मेल' ,
	'main' : 'मुख्य' ,
	'mainly' : 'में मुख्य' ,
	'maintain' : 'बनाए रखना' ,
	'maintenance' : 'रखरखाव' ,
	'major' : 'प्रमुख' ,
	'majority' : 'बहुमत' ,
	'make' : 'बनाना' ,
	'maker' : 'निर्माता' ,
	'makeup' : 'मेकअप' ,
	'male' : 'नर' ,
	'mall' : 'मॉल' ,
	'man' : 'पुरुष' ,
	'manage' : 'प्रबंधित करना' ,
	'management' : 'प्रबंध' ,
	'manager' : 'प्रबंधक' ,
	'manner' : 'तौर - तरीका' ,
	'manufacturer' : 'उत्पादक' ,
	'manufacturing' : 'उत्पादन' ,
	'many' : 'बहुत' ,
	'map' : 'नक्शा' ,
	'margin' : 'हाशिया' ,
	'mark' : 'निशान' ,
	'market' : 'मंडी' ,
	'marketing' : 'विपणन' ,
	'marriage' : 'शादी' ,
	'married' : 'विवाहित' ,
	'marry' : 'शादी कर' ,
	'mask' : 'मुखौटा' ,
	'mass' : 'द्रव्यमान' ,
	'massive' : 'बड़ा' ,
	'master' : 'गुरुजी' ,
	'match' : 'मिलान' ,
	'material' : 'सामग्री' ,
	'math' : 'गणित' ,
	'matter' : 'मामला' ,
	'may' : 'मई' ,
	'maybe' : 'शायद' ,
	'mayor' : 'महापौर' ,
	'me' : 'मुझे' ,
	'meal' : 'भोजन' ,
	'mean' : 'अर्थ' ,
	'meaning' : 'अर्थ' ,
	'meanwhile' : 'इस दौरान' ,
	'measure' : 'उपाय' ,
	'measurement' : 'माप' ,
	'meat' : 'मांस' ,
	'mechanism' : 'तंत्र' ,
	'media' : 'मीडिया' ,
	'medical' : 'मेडिकल' ,
	'medication' : 'दवाई' ,
	'medicine' : 'दवा' ,
	'medium' : 'मध्यम' ,
	'meet' : 'मिलना' ,
	'meeting' : 'बैठक' ,
	'member' : 'सदस्य' ,
	'membership' : 'सदस्यता' ,
	'memory' : 'याद' ,
	'mental' : 'मानसिक' ,
	'mention' : 'उल्लेख' ,
	'menu' : 'मेन्यू' ,
	'mere' : 'मात्र' ,
	'merely' : 'केवल' ,
	'mess' : 'गड़बड़' ,
	'message' : 'संदेश' ,
	'metal' : 'धातु' ,
	'meter' : 'मीटर' ,
	'method' : 'तरीका' ,
	'Mexican' : 'मैक्सिकन' ,
	'middle' : 'मध्य' ,
	'might' : 'पराक्रम' ,
	'military' : 'सैन्य' ,
	'milk' : 'दूध' ,
	'million' : 'दस लाख' ,
	'mind' : 'मन' ,
	'mine' : 'मेरा' ,
	'minister' : 'मंत्री' ,
	'minor' : 'अवयस्क' ,
	'minority' : 'अल्पसंख्यक' ,
	'minute' : 'मिनट' ,
	'miracle' : 'चमत्कार' ,
	'mirror' : 'आईना' ,
	'miss' : 'कुमारी' ,
	'missile' : 'मिसाइल' ,
	'mission' : 'मिशन' ,
	'mistake' : 'गलती' ,
	'mix' : 'मिक्स' ,
	'mixture' : 'मिश्रण' ,
	'mode' : 'तरीका' ,
	'model' : 'नमूना' ,
	'moderate' : 'उदारवादी' ,
	'modern' : 'आधुनिक' ,
	'modest' : 'मामूली' ,
	'mom' : 'मां' ,
	'moment' : 'पल' ,
	'money' : 'धन' ,
	'monitor' : 'मॉनिटर' ,
	'month' : 'महीना' ,
	'mood' : 'मनोदशा' ,
	'moon' : 'चांद' ,
	'moral' : 'शिक्षा' ,
	'more' : 'अधिक' ,
	'moreover' : 'इसके अलावा' ,
	'morning' : 'प्रभात' ,
	'mortgage' : 'बंधक' ,
	'most' : 'अधिकांश' ,
	'mostly' : 'ज्यादा टार' ,
	'mother' : 'मां' ,
	'motion' : 'गति' ,
	'motivation' : 'प्रेरणा' ,
	'motor' : 'मोटर' ,
	'mount' : 'पर्वत' ,
	'mountain' : 'पहाड़' ,
	'mouse' : 'चूहा' ,
	'mouth' : 'मुंह' ,
	'move' : 'कदम' ,
	'movement' : 'गति' ,
	'movie' : 'चलचित्र' ,
	'Mr' : 'श्री' ,
	'Mrs' : 'श्रीमती' ,
	'Ms' : 'एमएस' ,
	'much' : 'बहुत' ,
	'multiple' : 'विभिन्न' ,
	'murder' : 'हत्या' ,
	'muscle' : 'मांसपेशी' ,
	'museum' : 'संग्रहालय' ,
	'music' : 'संगीत' ,
	'musical' : 'संगीत' ,
	'musician' : 'संगीतकार' ,
	'Muslim' : 'मुसलमान' ,
	'must' : 'जरूर' ,
	'mutual' : 'आपसी' ,
	'my' : 'मेरे' ,
	'myself' : 'खुद' ,
	'mystery' : 'रहस्य' ,
	'myth' : 'कल्पित कथा' ,
	'naked' : 'नंगा' ,
	'name' : 'नाम' ,
	'narrative' : 'वर्णन' ,
	'narrow' : 'संकीर्ण' ,
	'nation' : 'राष्ट्र' ,
	'national' : 'राष्ट्रीय' ,
	'native' : 'मूल निवासी' ,
	'natural' : 'प्राकृतिक' ,
	'naturally' : 'सहज रूप में' ,
	'nature' : 'प्रकृति' ,
	'near' : 'पास' ,
	'nearby' : 'समीप' ,
	'nearly' : 'लगभग' ,
	'necessarily' : 'अनिवार्य रूप से' ,
	'necessary' : 'ज़रूरी' ,
	'neck' : 'गर्दन' ,
	'need' : 'ज़रूरत' ,
	'negative' : 'नकारात्मक' ,
	'negotiate' : 'मोल - भाव करना' ,
	'negotiation' : 'बातचीत' ,
	'neighbor' : 'पड़ोसी' ,
	'neighborhood' : 'अड़ोस - पड़ोस' ,
	'neither' : 'न' ,
	'nerve' : 'नस' ,
	'nervous' : 'बेचैन' ,
	'net' : 'जाल' ,
	'network' : 'नेटवर्क' ,
	'never' : 'कभी नहीँ' ,
	'nevertheless' : 'फिर भी' ,
	'new' : 'नया' ,
	'newly' : 'नए नए' ,
	'news' : 'समाचार' ,
	'newspaper' : 'अखबार' ,
	'next' : 'अगला' ,
	'nice' : 'अच्छा' ,
	'night' : 'रात' ,
	'nine' : 'नौ' ,
	'no' : 'ना' ,
	'nobody' : 'कोई नहीं' ,
	'nod' : 'सिर हिलाकर सहमति देना' ,
	'noise' : 'शोर' ,
	'nomination' : 'नामांकन' ,
	'none' : 'कोई नहीं' ,
	'nonetheless' : 'बहरहाल' ,
	'nor' : 'और न' ,
	'normal' : 'साधारण' ,
	'normally' : 'सामान्य रूप से' ,
	'north' : 'उत्तर' ,
	'northern' : 'उत्तरी' ,
	'nose' : 'नाक' ,
	'not' : 'नहीं' ,
	'note' : 'ध्यान दें' ,
	'nothing' : 'कुछ नहीं' ,
	'notice' : 'सूचना' ,
	'notion' : 'धारणा' ,
	'novel' : 'उपन्यास' ,
	'now' : 'अभी' ,
	'nowhere' : 'कहीं भी नहीं' ,
	'nt' : 'नहीं' ,
	'nuclear' : 'नाभिकीय' ,
	'number' : 'संख्या' ,
	'numerous' : 'बहुत' ,
	'nurse' : 'नर्स' ,
	'nut' : 'काष्ठफल' ,
	'object' : 'वस्तु' ,
	'objective' : 'उद्देश्य' ,
	'obligation' : 'बाध्यता' ,
	'observation' : 'अवलोकन' ,
	'observe' : 'अवलोकन करना' ,
	'observer' : 'देखने वाला' ,
	'obtain' : 'प्राप्त' ,
	'obvious' : 'ज़ाहिर' ,
	'obviously' : 'स्पष्टतः' ,
	'occasion' : 'अवसर' ,
	'occasionally' : 'कभी - कभी' ,
	'occupation' : 'पेशा' ,
	'occupy' : 'पर कब्जा' ,
	'occur' : 'घटित होना' ,
	'ocean' : 'सागर' ,
	'odd' : 'अजीब' ,
	'odds' : 'अंतर' ,
	'of' : 'का' ,
	'off' : 'बंद' ,
	'offense' : 'अपराध' ,
	'offensive' : 'अप्रिय' ,
	'offer' : 'प्रस्ताव' ,
	'office' : 'कार्यालय' ,
	'officer' : 'अफ़सर' ,
	'official' : 'अधिकारी' ,
	'often' : 'अक्सर' ,
	'oh' : 'ओह' ,
	'oil' : 'तेल' ,
	'ok' : 'ठीक' ,
	'okay' : 'ठीक' ,
	'old' : 'पुराना' ,
	'Olympic' : 'ओलिंपिक' ,
	'on' : 'पर' ,
	'once' : 'एक बार' ,
	'one' : 'एक' ,
	'ongoing' : 'चल रही है' ,
	'onion' : 'प्याज' ,
	'online' : 'ऑनलाइन' ,
	'only' : 'केवल' ,
	'onto' : 'पर' ,
	'open' : 'खुला हुआ' ,
	'opening' : 'प्रारंभिक' ,
	'operate' : 'संचालित' ,
	'operating' : 'ऑपरेटिंग' ,
	'operation' : 'कार्यवाही' ,
	'operator' : 'ऑपरेटर' ,
	'opinion' : 'राय' ,
	'opponent' : 'प्रतिद्वंद्वी' ,
	'opportunity' : 'मौका' ,
	'oppose' : 'का विरोध' ,
	'opposite' : 'विलोम' ,
	'opposition' : 'विरोध' ,
	'option' : 'विकल्प' ,
	'or' : 'या' ,
	'orange' : 'संतरा' ,
	'order' : 'गण' ,
	'ordinary' : 'साधारण' ,
	'organic' : 'कार्बनिक' ,
	'organization' : 'संगठन' ,
	'organize' : 'व्यवस्थित' ,
	'orientation' : 'अभिविन्यास' ,
	'origin' : 'मूल' ,
	'original' : 'मूल' ,
	'originally' : 'मौलिक रूप से' ,
	'other' : 'अन्य' ,
	'others' : 'अन्य' ,
	'otherwise' : 'अन्यथा' ,
	'ought' : 'चाहिए' ,
	'our' : 'हमारी' ,
	'ourselves' : 'हम स्वयं' ,
	'out' : 'बाहर' ,
	'outcome' : 'परिणाम' ,
	'outside' : 'बाहर' ,
	'oven' : 'ओवन' ,
	'over' : 'ऊपर' ,
	'overall' : 'संपूर्ण' ,
	'overcome' : 'काबू पाना' ,
	'overlook' : 'ओवरलुक' ,
	'owe' : 'आभारी होना' ,
	'own' : 'अपना' ,
	'owner' : 'मालिक' ,
	'pace' : 'गति' ,
	'pack' : 'पैक' ,
	'package' : 'पैकेज' ,
	'page' : 'पृष्ठ' ,
	'pain' : 'दर्द' ,
	'painful' : 'दर्दनाक' ,
	'paint' : 'रंग' ,
	'painter' : 'चित्रकार' ,
	'painting' : 'चित्र' ,
	'pair' : 'जोड़ा' ,
	'pale' : 'फीका' ,
	'Palestinian' : 'फ़िलिस्तीनी' ,
	'palm' : 'हथेली' ,
	'pan' : 'कड़ाही' ,
	'panel' : 'पैनल' ,
	'pant' : 'पंत' ,
	'paper' : 'कागज़' ,
	'parent' : 'माता-पिता' ,
	'park' : 'पार्क' ,
	'parking' : 'पार्किंग' ,
	'part' : 'अंश' ,
	'participant' : 'प्रतिभागी' ,
	'participate' : 'भाग लेना' ,
	'participation' : 'भाग लेना' ,
	'particular' : 'विशेष' ,
	'particularly' : 'विशेष रूप से' ,
	'partly' : 'आंशिक रूप में' ,
	'partner' : 'साथी' ,
	'partnership' : 'साझेदारी' ,
	'party' : 'दल' ,
	'pass' : 'उत्तीर्ण' ,
	'passage' : 'मार्ग' ,
	'passenger' : 'यात्री' ,
	'passion' : 'जुनून' ,
	'past' : 'भूतकाल' ,
	'patch' : 'पैच' ,
	'path' : 'पथ' ,
	'patient' : 'मरीज' ,
	'pattern' : 'प्रतिरूप' ,
	'pause' : 'ठहराव' ,
	'pay' : 'भुगतान करते हैं' ,
	'payment' : 'भुगतान' ,
	'PC' : 'पीसी' ,
	'peace' : 'शांति' ,
	'peak' : 'शिखर' ,
	'peer' : 'समकक्ष' ,
	'penalty' : 'दंड' ,
	'people' : 'लोग' ,
	'pepper' : 'मिर्च' ,
	'per' : 'प्रति' ,
	'perceive' : 'समझना' ,
	'percentage' : 'प्रतिशत' ,
	'perception' : 'अनुभूति' ,
	'perfect' : 'उत्तम' ,
	'perfectly' : 'पूरी तरह से' ,
	'perform' : 'प्रदर्शन' ,
	'performance' : 'प्रदर्शन' ,
	'perhaps' : 'शायद' ,
	'period' : 'अवधि' ,
	'permanent' : 'स्थायी' ,
	'permission' : 'अनुमति' ,
	'permit' : 'परमिट' ,
	'person' : 'व्यक्ति' ,
	'personal' : 'व्यक्तिगत' ,
	'personality' : 'व्यक्तित्व' ,
	'personally' : 'व्यक्तिगत रूप से' ,
	'personnel' : 'कार्मिक' ,
	'perspective' : 'परिप्रेक्ष्य' ,
	'persuade' : 'राज़ी करना' ,
	'pet' : 'पालतू पशु' ,
	'phase' : 'अवस्था' ,
	'phenomenon' : 'घटना' ,
	'philosophy' : 'दर्शन' ,
	'phone' : 'फ़ोन' ,
	'photo' : 'तस्वीर' ,
	'photograph' : 'फोटो' ,
	'photographer' : 'फोटोग्राफर' ,
	'phrase' : 'मुहावरा' ,
	'physical' : 'शारीरिक' ,
	'physically' : 'शारीरिक रूप से' ,
	'physician' : 'चिकित्सक' ,
	'piano' : 'पियानो' ,
	'pick' : 'चुनना' ,
	'picture' : 'चित्र' ,
	'pie' : 'पाई' ,
	'piece' : 'टुकड़ा' ,
	'pile' : 'ढेर' ,
	'pilot' : 'पायलट' ,
	'pine' : 'देवदार' ,
	'pink' : 'गुलाबी' ,
	'pipe' : 'पाइप' ,
	'pitch' : 'आवाज़ का उतार - चढ़ाव' ,
	'place' : 'स्थान' ,
	'plan' : 'योजना' ,
	'plane' : 'विमान' ,
	'planet' : 'ग्रह' ,
	'planning' : 'योजना' ,
	'plant' : 'पौधा' ,
	'plastic' : 'प्लास्टिक' ,
	'plate' : 'प्लेट' ,
	'platform' : 'मंच' ,
	'play' : 'प्ले Play' ,
	'player' : 'खिलाड़ी' ,
	'please' : 'कृपया' ,
	'pleasure' : 'आनंद' ,
	'plenty' : 'खूब' ,
	'plot' : 'भूखंड' ,
	'plus' : 'प्लस' ,
	'PM' : 'बजे' ,
	'pocket' : 'जेब' ,
	'poem' : 'कविता' ,
	'poet' : 'कवि' ,
	'poetry' : 'शायरी' ,
	'point' : 'बिंदु' ,
	'pole' : 'खंभा' ,
	'police' : 'पुलिस' ,
	'policy' : 'नीति' ,
	'political' : 'राजनीतिक' ,
	'politically' : 'राजनीतिक' ,
	'politician' : 'राजनीतिज्ञ' ,
	'politics' : 'राजनीति' ,
	'poll' : 'मतदान' ,
	'pollution' : 'प्रदूषण' ,
	'pool' : 'पूल' ,
	'poor' : 'गरीब' ,
	'pop' : 'पॉप' ,
	'popular' : 'लोकप्रिय' ,
	'population' : 'आबादी' ,
	'porch' : 'बरामदा' ,
	'port' : 'बंदरगाह' ,
	'portion' : 'हिस्से' ,
	'portrait' : 'चित्र' ,
	'portray' : 'चित्रकला' ,
	'pose' : 'खड़ा करना' ,
	'position' : 'स्थान' ,
	'positive' : 'सकारात्मक' ,
	'possess' : 'काबू करना' ,
	'possibility' : 'संभावना' ,
	'possible' : 'मुमकिन' ,
	'possibly' : 'संभवत:' ,
	'post' : 'पद' ,
	'pot' : 'मटका' ,
	'potato' : 'आलू' ,
	'potential' : 'क्षमता' ,
	'potentially' : 'संभावित' ,
	'pound' : 'पौंड' ,
	'poverty' : 'गरीबी' ,
	'powder' : 'पाउडर' ,
	'power' : 'शक्ति' ,
	'powerful' : 'शक्तिशाली' ,
	'practical' : 'व्यावहारिक' ,
	'practice' : 'अभ्यास' ,
	'pray' : 'प्रार्थना' ,
	'prayer' : 'प्रार्थना' ,
	'precisely' : 'यकीनन' ,
	'predict' : 'भविष्यवाणी करना' ,
	'prefer' : 'पसंद करना' ,
	'preference' : 'पसंद' ,
	'pregnancy' : 'गर्भावस्था' ,
	'pregnant' : 'गर्भवती' ,
	'preparation' : 'तैयारी' ,
	'prepare' : 'तैयार' ,
	'prescription' : 'नुस्खा' ,
	'presence' : 'उपस्थिति' ,
	'present' : 'वर्तमान' ,
	'presentation' : 'प्रस्तुतीकरण' ,
	'preserve' : 'रक्षित' ,
	'president' : 'अध्यक्ष' ,
	'presidential' : 'अध्यक्षीय' ,
	'press' : 'दबाएँ' ,
	'pressure' : 'दबाव' ,
	'pretend' : 'बहाना करना' ,
	'pretty' : 'सुंदर हे' ,
	'prevent' : 'रोकना' ,
	'previous' : 'पहले का' ,
	'previously' : 'इससे पहले' ,
	'price' : 'कीमत' ,
	'pride' : 'गौरव' ,
	'priest' : 'पुजारी' ,
	'primarily' : 'प्रमुख रूप से' ,
	'primary' : 'मुख्य' ,
	'prime' : 'प्रधान' ,
	'principal' : 'प्रधान अध्यापक' ,
	'principle' : 'सिद्धांत' ,
	'print' : 'प्रिंट' ,
	'prior' : 'पूर्व' ,
	'priority' : 'वरीयता' ,
	'prison' : 'कारागार' ,
	'prisoner' : 'बंदी' ,
	'privacy' : 'गोपनीयता' ,
	'private' : 'निजी' ,
	'probably' : 'संभवत' ,
	'problem' : 'संकट' ,
	'procedure' : 'प्रक्रिया' ,
	'proceed' : 'आगे बढ़ना' ,
	'process' : 'प्रक्रिया' ,
	'produce' : 'उत्पाद' ,
	'producer' : 'निर्माता' ,
	'product' : 'उत्पाद' ,
	'production' : 'उत्पादन' ,
	'profession' : 'पेशा' ,
	'professional' : 'पेशेवर' ,
	'professor' : 'प्रोफ़ेसर' ,
	'profile' : 'प्रोफ़ाइल' ,
	'profit' : 'फायदा' ,
	'program' : 'कार्यक्रम' ,
	'progress' : 'प्रगति' ,
	'project' : 'परियोजना' ,
	'prominent' : 'प्रमुख' ,
	'promise' : 'वादा' ,
	'promote' : 'को बढ़ावा देना' ,
	'prompt' : 'तत्पर' ,
	'proof' : 'प्रमाण' ,
	'proper' : 'उचित' ,
	'properly' : 'अच्छी तरह से' ,
	'property' : 'संपत्ति' ,
	'proportion' : 'अनुपात' ,
	'proposal' : 'प्रस्ताव' ,
	'propose' : 'प्रस्ताव' ,
	'proposed' : 'प्रस्तावित' ,
	'prosecutor' : 'अभियोक्ता' ,
	'prospect' : 'आशा' ,
	'protect' : 'रक्षा करना' ,
	'protection' : 'संरक्षण' ,
	'protein' : 'प्रोटीन' ,
	'protest' : 'विरोध' ,
	'proud' : 'गर्व' ,
	'prove' : 'साबित करना' ,
	'provide' : 'प्रदान करना' ,
	'provider' : 'प्रदाता' ,
	'province' : 'प्रांत' ,
	'provision' : 'प्रावधान' ,
	'psychological' : 'मनोवैज्ञानिक' ,
	'psychologist' : 'मनोविज्ञानी' ,
	'psychology' : 'मनोविज्ञान' ,
	'public' : 'जनता' ,
	'publication' : 'प्रकाशन' ,
	'publicly' : 'सार्वजनिक रूप' ,
	'publish' : 'प्रकाशित करना' ,
	'publisher' : 'प्रकाशक' ,
	'pull' : 'खींचना' ,
	'punishment' : 'सज़ा' ,
	'purchase' : 'खरीद फरोख्त' ,
	'pure' : 'शुद्ध' ,
	'purpose' : 'प्रयोजन' ,
	'pursue' : 'पाने की कोशिश करना' ,
	'push' : 'धकेलना' ,
	'put' : 'रखना' ,
	'qualify' : 'अर्हता' ,
	'quality' : 'गुणवत्ता' ,
	'quarter' : 'त्रिमास' ,
	'quarterback' : 'क्वार्टरबैक' ,
	'question' : 'प्रश्न' ,
	'quick' : 'झट से' ,
	'quickly' : 'जल्दी जल्दी' ,
	'quiet' : 'चुप' ,
	'quietly' : 'चुपचाप' ,
	'quit' : 'छोड़ना' ,
	'quite' : 'अत्यंत' ,
	'quote' : 'उद्धरण' ,
	'race' : 'जाति' ,
	'racial' : 'जातीय' ,
	'radical' : 'मौलिक' ,
	'radio' : 'रेडियो' ,
	'rail' : 'रेल' ,
	'rain' : 'वर्षा' ,
	'raise' : 'चढ़ाई' ,
	'range' : 'श्रेणी' ,
	'rank' : 'पद' ,
	'rapid' : 'तेज़' ,
	'rapidly' : 'तेज़ी से' ,
	'rare' : 'दुर्लभ' ,
	'rarely' : 'शायद ही कभी' ,
	'rate' : 'भाव' ,
	'rather' : 'बल्कि' ,
	'rating' : 'रेटिंग' ,
	'ratio' : 'अनुपात' ,
	'raw' : 'कच्चा' ,
	'reach' : 'पहुंच' ,
	'react' : 'प्रतिक्रिया' ,
	'reaction' : 'प्रतिक्रिया' ,
	'read' : 'पढ़ना' ,
	'reader' : 'रीडर' ,
	'reading' : 'अध्ययन' ,
	'ready' : 'तैयार' ,
	'real' : 'असली' ,
	'reality' : 'असलियत' ,
	'realize' : 'एहसास' ,
	'really' : 'सचमुच' ,
	'reason' : 'कारण' ,
	'reasonable' : 'यथोचित' ,
	'recall' : 'याद' ,
	'receive' : 'प्राप्त करना' ,
	'recent' : 'हालिया' ,
	'recently' : 'हाल ही में' ,
	'recipe' : 'विधि' ,
	'recognition' : 'मान्यता' ,
	'recognize' : 'पहचानना' ,
	'recommend' : 'अनुशंसा करना' ,
	'recommendation' : 'सिफ़ारिश करना' ,
	'record' : 'अभिलेख' ,
	'recording' : 'रिकॉर्डिंग' ,
	'recover' : 'की वसूली' ,
	'recovery' : 'स्वास्थ्य लाभ' ,
	'recruit' : 'रंगरूट' ,
	'red' : 'लाल' ,
	'reduce' : 'कम करना' ,
	'reduction' : 'कमी' ,
	'refer' : 'उद्घृत करना' ,
	'reference' : 'संदर्भ' ,
	'reflect' : 'प्रतिबिंबित होना' ,
	'reflection' : 'प्रतिबिंब' ,
	'reform' : 'सुधार' ,
	'refugee' : 'शरणार्थी' ,
	'refuse' : 'इनकार' ,
	'regard' : 'संबद्ध' ,
	'regarding' : 'के बारे में' ,
	'regardless' : 'ध्यान दिए बगैर' ,
	'regime' : 'प्रशासन' ,
	'region' : 'क्षेत्र' ,
	'regional' : 'क्षेत्रीय' ,
	'register' : 'रजिस्टर करें' ,
	'regular' : 'नियमित' ,
	'regularly' : 'नियमित तौर पर' ,
	'regulate' : 'विनियमित' ,
	'regulation' : 'विनियमन' ,
	'reinforce' : 'सुदृढ़' ,
	'reject' : 'अस्वीकार' ,
	'relate' : 'संबंधित' ,
	'relation' : 'संबंध' ,
	'relationship' : 'संबंध' ,
	'relative' : 'रिश्तेदार' ,
	'relatively' : 'अपेक्षाकृत' ,
	'relax' : 'आराम करना' ,
	'release' : 'रिहाई' ,
	'relevant' : 'से मिलता जुलता' ,
	'relief' : 'छुटकारा' ,
	'religion' : 'धर्म' ,
	'religious' : 'धार्मिक' ,
	'rely' : 'भरोसा करना' ,
	'remain' : 'रहना' ,
	'remaining' : 'बचा हुआ' ,
	'remarkable' : 'उत्कृष्ट' ,
	'remember' : 'याद रखना' ,
	'remind' : 'ध्यान दिलाना' ,
	'remote' : 'दूरस्थ' ,
	'remove' : 'निकालना' ,
	'repeat' : 'दोहराना' ,
	'repeatedly' : 'बार बार' ,
	'replace' : 'बदलने के' ,
	'reply' : 'जवाब दे दो' ,
	'report' : 'रिपोर्ट good' ,
	'reporter' : 'रिपोर्टर' ,
	'represent' : 'प्रतिनिधित्व करना' ,
	'representation' : 'प्रतिनिधित्व' ,
	'representative' : 'प्रतिनिधि' ,
	'Republican' : 'रिपब्लिकन' ,
	'reputation' : 'प्रतिष्ठा' ,
	'request' : 'प्रार्थना' ,
	'require' : 'की आवश्यकता होती है' ,
	'requirement' : 'मांग' ,
	'research' : 'अनुसंधान' ,
	'researcher' : 'शोधकर्ता' ,
	'resemble' : 'समान होना' ,
	'reservation' : 'आरक्षण' ,
	'resident' : 'निवासी' ,
	'resist' : 'विरोध' ,
	'resistance' : 'प्रतिरोध' ,
	'resolution' : 'संकल्प' ,
	'resolve' : 'संकल्प' ,
	'resort' : 'सहारा' ,
	'resource' : 'संसाधन' ,
	'respect' : 'आदर करना' ,
	'respond' : 'जवाब' ,
	'respondent' : 'प्रतिवादी' ,
	'response' : 'प्रतिक्रिया' ,
	'responsibility' : 'ज़िम्मेदारी' ,
	'responsible' : 'उत्तरदायी' ,
	'rest' : 'विश्राम' ,
	'restaurant' : 'रेस्टोरेंट' ,
	'restore' : 'बहाल' ,
	'restriction' : 'बंधन' ,
	'result' : 'नतीजा' ,
	'retain' : 'बनाए रखना' ,
	'retire' : 'रिटायर' ,
	'retirement' : 'निवृत्ति' ,
	'return' : 'वापसी' ,
	'reveal' : 'प्रकट करना' ,
	'revenue' : 'राजस्व' ,
	'review' : 'समीक्षा' ,
	'revolution' : 'क्रांति' ,
	'rhythm' : 'ताल' ,
	'rice' : 'चावल' ,
	'rich' : 'धनी' ,
	'rid' : 'छुटकारा दिलाना' ,
	'ride' : 'सवारी' ,
	'rifle' : 'राइफल' ,
	'right' : 'सही' ,
	'ring' : 'चक्राकार पदार्थ' ,
	'rise' : 'वृद्धि' ,
	'risk' : 'जोखिम' ,
	'river' : 'नदी' ,
	'road' : 'सड़क' ,
	'rock' : 'चट्टान' ,
	'role' : 'भूमिका' ,
	'roll' : 'घूमना' ,
	'romantic' : 'प्रेम प्रसंगयुक्त' ,
	'roof' : 'छत' ,
	'room' : 'कक्ष' ,
	'root' : 'जड़' ,
	'rope' : 'रस्सी' ,
	'rose' : 'गुलाब' ,
	'rough' : 'खुरदुरा' ,
	'roughly' : 'मोटे तौर पर' ,
	'round' : 'गोल' ,
	'route' : 'मार्ग' ,
	'routine' : 'दिनचर्या' ,
	'row' : 'पंक्ति' ,
	'rub' : 'रगड़' ,
	'rule' : 'नियम' ,
	'run' : 'दौड़ना' ,
	'running' : 'दौड़ना' ,
	'rural' : 'ग्रामीण' ,
	'rush' : 'भीड़' ,
	'Russian' : 'रूसी' ,
	'sacred' : 'पवित्र' ,
	'sad' : 'दुखी' ,
	'safe' : 'सुरक्षित' ,
	'safety' : 'सुरक्षा' ,
	'sake' : 'खातिर' ,
	'salad' : 'सलाद' ,
	'salary' : 'वेतन' ,
	'sale' : 'बिक्री' ,
	'sales' : 'बिक्री' ,
	'salt' : 'नमक' ,
	'same' : 'वही' ,
	'sample' : 'नमूना' ,
	'sanction' : 'प्रतिबंध' ,
	'sand' : 'रेत' ,
	'satellite' : 'उपग्रह' ,
	'satisfaction' : 'संतुष्टि' ,
	'satisfy' : 'बदला देना' ,
	'sauce' : 'चटनी' ,
	'save' : 'सहेजें' ,
	'saving' : 'सहेजा जा रहा है' ,
	'say' : 'कहो' ,
	'scale' : 'स्केल' ,
	'scandal' : 'कांड' ,
	'scared' : 'डरा हुआ' ,
	'scenario' : 'परिदृश्य' ,
	'scene' : 'दृश्य' ,
	'schedule' : 'अनुसूची' ,
	'scheme' : 'योजना' ,
	'scholar' : 'पंडित' ,
	'scholarship' : 'छात्रवृत्ति' ,
	'school' : 'स्कूल' ,
	'science' : 'विज्ञान' ,
	'scientific' : 'वैज्ञानिक' ,
	'scientist' : 'वैज्ञानिक' ,
	'scope' : 'दायरा' ,
	'score' : 'स्कोर' ,
	'scream' : 'चीख' ,
	'screen' : 'स्क्रीन' ,
	'script' : 'लिपि' ,
	'sea' : 'समुद्र' ,
	'search' : 'तलाशी' ,
	'season' : 'मौसम' ,
	'seat' : 'सीट' ,
	'second' : 'दूसरा' ,
	'secret' : 'गुप्त' ,
	'secretary' : 'सचिव' ,
	'section' : 'अनुभाग' ,
	'sector' : 'क्षेत्र' ,
	'secure' : 'सुरक्षित' ,
	'security' : 'सुरक्षा' ,
	'see' : 'देखो' ,
	'seed' : 'बीज' ,
	'seek' : 'मांगना' ,
	'seem' : 'लगना' ,
	'segment' : 'खंड' ,
	'seize' : 'को जब्त' ,
	'select' : 'चुनते हैं' ,
	'selection' : 'चयन' ,
	'self' : 'स्वयं' ,
	'sell' : 'बेचना' ,
	'Senate' : 'प्रबंधकारिणी समिति' ,
	'senator' : 'सीनेटर' ,
	'send' : 'भेजना' ,
	'senior' : 'वरिष्ठ' ,
	'sense' : 'समझ' ,
	'sensitive' : 'संवेदनशील' ,
	'sentence' : 'वाक्य' ,
	'separate' : 'अलग' ,
	'sequence' : 'अनुक्रम' ,
	'series' : 'श्रृंखला' ,
	'serious' : 'गंभीर' ,
	'seriously' : 'गंभीरता से' ,
	'serve' : 'सेवा कर' ,
	'service' : 'सेवा' ,
	'session' : 'सत्र' ,
	'set' : 'समूह' ,
	'setting' : 'स्थापना' ,
	'settle' : 'रुकना' ,
	'settlement' : 'समझौता' ,
	'seven' : 'सात' ,
	'several' : 'कई' ,
	'severe' : 'गंभीर' ,
	'sex' : 'लिंग' ,
	'sexual' : 'यौन' ,
	'shade' : 'छाया' ,
	'shadow' : 'साया' ,
	'shake' : 'हिलाना' ,
	'shall' : 'करेगा' ,
	'shape' : 'आकार' ,
	'share' : 'साझा करना' ,
	'sharp' : 'तीखा' ,
	'she' : 'वह' ,
	'sheet' : 'चादर' ,
	'shelf' : 'शेल्फ' ,
	'shell' : 'सीप' ,
	'shelter' : 'आश्रय' ,
	'shift' : 'खिसक जाना' ,
	'shine' : 'चमक' ,
	'ship' : 'समुंद्री जहाज' ,
	'shirt' : 'कमीज' ,
	'shit' : 'मल' ,
	'shock' : 'झटका' ,
	'shoe' : 'जूता' ,
	'shoot' : 'गोली मारना' ,
	'shooting' : 'शूटिंग' ,
	'shop' : 'दुकान' ,
	'shopping' : 'खरीदारी' ,
	'shore' : 'किनारा' ,
	'short' : 'कम' ,
	'shortly' : 'कुछ ही देर में' ,
	'shot' : 'शॉट' ,
	'should' : 'चाहिए' ,
	'shoulder' : 'कंधा' ,
	'shout' : 'चिल्लाहट' ,
	'show' : 'प्रदर्शन' ,
	'shower' : 'बौछार' ,
	'shrug' : 'कंधे उचकाने की क्रिया' ,
	'shut' : 'बंद' ,
	'sick' : 'बीमार' ,
	'side' : 'पक्ष' ,
	'sigh' : 'विलाप' ,
	'sight' : 'दृष्टि' ,
	'sign' : 'संकेत' ,
	'signal' : 'संकेत' ,
	'significance' : 'महत्व' ,
	'significant' : 'सार्थक' ,
	'significantly' : 'काफी' ,
	'silence' : 'शांति' ,
	'silent' : 'मूक' ,
	'silver' : 'चांदी' ,
	'similar' : 'समान' ,
	'similarly' : 'उसी प्रकार' ,
	'simple' : 'सरल' ,
	'simply' : 'केवल' ,
	'since' : 'जबसे' ,
	'sing' : 'गाओ' ,
	'singer' : 'गायक' ,
	'ski' : 'स्की' ,
	'skill' : 'कौशल' ,
	'sleep' : 'नींद' ,
	'slice' : 'टुकड़ा' ,
	'slide' : 'फिसल पट्टी' ,
	'slight' : 'थोड़ा' ,
	'slightly' : 'थोड़ा' ,
	'slip' : 'पर्ची' ,
	'slow' : 'धीरे' ,
	'slowly' : 'धीरे से' ,
	'small' : 'छोटा' ,
	'smart' : 'बुद्धिमान' ,
	'smell' : 'गंध' ,
	'smile' : 'मुस्कुराओ' ,
	'smoke' : 'धुआं' ,
	'smooth' : 'निर्बाध' ,
	'snap' : 'चटकाना' ,
	'snow' : 'बर्फ' ,
	'so' : 'इसलिए' ,
	'so-called' : 'तथाकथित' ,
	'soccer' : 'फुटबॉल' ,
	'social' : 'सामाजिक' ,
	'society' : 'समाज' ,
	'soft' : 'मुलायम' ,
	'software' : 'सॉफ्टवेयर' ,
	'soil' : 'धरती' ,
	'solar' : 'सौर' ,
	'soldier' : 'फोजी' ,
	'solid' : 'ठोस' ,
	'solution' : 'समाधान' ,
	'somewhat' : 'कुछ हद तक' ,
	'somewhere' : 'कहीं' ,
	'son' : 'बेटा' ,
	'song' : 'गीत' ,
	'soon' : 'जल्द ही' ,
	'sophisticated' : 'जटिल' ,
	'sorry' : 'क्षमा मांगना' ,
	'sort' : 'तरह' ,
	'soul' : 'आत्मा' ,
	'sound' : 'ध्वनि' ,
	'soup' : 'सूप' ,
	'source' : 'स्रोत' ,
	'south' : 'दक्षिण' ,
	'southern' : 'दक्षिण' ,
	'Soviet' : 'सोवियत' ,
	'space' : 'स्थान' ,
	'Spanish' : 'स्पेनिश' ,
	'speak' : 'बोलना' ,
	'speaker' : 'वक्ता' ,
	'special' : 'विशेष' ,
	'specialist' : 'SPECIALIST' ,
	'species' : 'प्रजातियां' ,
	'specific' : 'विशिष्ट' ,
	'specifically' : 'विशेष रूप से' ,
	'speech' : 'भाषण' ,
	'speed' : 'स्पीड' ,
	'spend' : 'खर्च करना' ,
	'spending' : 'खर्च' ,
	'spin' : 'घुमाव' ,
	'spirit' : 'आत्मा' ,
	'spiritual' : 'आध्यात्मिक' ,
	'split' : 'विभाजित करना' ,
	'spokesman' : 'प्रवक्ता' ,
	'sport' : 'खेल' ,
	'spot' : 'स्थान' ,
	'spread' : 'फैलाव' ,
	'spring' : 'वसंत' ,
	'square' : 'वर्ग' ,
	'squeeze' : 'निचोड़' ,
	'stability' : 'स्थिरता' ,
	'stable' : 'स्थिर' ,
	'staff' : 'कर्मचारी' ,
	'stage' : 'मंच' ,
	'stair' : 'सीढ़ी' ,
	'stake' : 'दांव लगाना' ,
	'stand' : 'खड़ा होना' ,
	'standard' : 'मानक' ,
	'standing' : 'खड़ा है' ,
	'star' : 'तारा' ,
	'stare' : 'एकटक देखना' ,
	'start' : 'शुरु' ,
	'state' : 'राज्य' ,
	'statement' : 'बयान' ,
	'station' : 'स्टेशन' ,
	'statistics' : 'आंकड़े' ,
	'status' : 'स्थिति' ,
	'stay' : 'रहना' ,
	'steady' : 'नियमित' ,
	'steal' : 'चुराना' ,
	'steel' : 'इस्पात' ,
	'step' : 'कदम' ,
	'stick' : 'छड़ी' ,
	'still' : 'फिर भी' ,
	'stir' : 'हलचल' ,
	'stock' : 'भण्डार' ,
	'stomach' : 'पेट' ,
	'stone' : 'पथरी' ,
	'stop' : 'विराम' ,
	'storage' : 'भंडारण' ,
	'store' : 'दुकान' ,
	'storm' : 'आंधी' ,
	'story' : 'कहानी' ,
	'straight' : 'सीधा' ,
	'strange' : 'अनोखा' ,
	'stranger' : 'अजनबी' ,
	'strategic' : 'सामरिक' ,
	'strategy' : 'रणनीति' ,
	'stream' : 'धारा' ,
	'street' : 'सड़क' ,
	'strength' : 'ताकत' ,
	'strengthen' : 'को मजबूत' ,
	'stress' : 'तनाव' ,
	'stretch' : 'फैलाव' ,
	'strike' : 'धरना' ,
	'string' : 'डोरी' ,
	'strip' : 'पट्टी' ,
	'stroke' : 'आघात' ,
	'strong' : 'बलवान' ,
	'strongly' : 'दृढ़ता से' ,
	'structure' : 'संरचना' ,
	'struggle' : 'संघर्ष' ,
	'student' : 'छात्र' ,
	'studio' : 'स्टूडियो' ,
	'study' : 'पढाई' ,
	'stuff' : 'सामग्री' ,
	'stupid' : 'बेवकूफ' ,
	'style' : 'अंदाज' ,
	'subject' : 'विषय' ,
	'submit' : 'प्रस्तुत' ,
	'subsequent' : 'बाद का' ,
	'substance' : 'पदार्थ' ,
	'substantial' : 'संतोषजनक' ,
	'succeed' : 'सफल होने के' ,
	'success' : 'सफलता' ,
	'successful' : 'सफल' ,
	'successfully' : 'सफलतापूर्वक' ,
	'such' : 'ऐसा' ,
	'sudden' : 'अचानक' ,
	'suddenly' : 'अचानक से' ,
	'sue' : 'मुक़दमा चलाना' ,
	'suffer' : 'भुगतना' ,
	'sufficient' : 'पर्याप्त' ,
	'sugar' : 'चीनी' ,
	'suggest' : 'सुझाना' ,
	'suggestion' : 'सुझाव' ,
	'suicide' : 'आत्मघाती' ,
	'suit' : 'पोशाक' ,
	'summer' : 'गर्मी' ,
	'summit' : 'शिखर सम्मेलन' ,
	'sun' : 'रवि' ,
	'super' : 'बहुत अच्छा' ,
	'supply' : 'आपूर्ति' ,
	'support' : 'सहयोग' ,
	'supporter' : 'समर्थक' ,
	'suppose' : 'मान लीजिए' ,
	'supposed' : 'माना' ,
	'Supreme' : 'सुप्रीम' ,
	'sure' : 'ज़रूर' ,
	'surely' : 'निश्चित रूप से' ,
	'surface' : 'सतह' ,
	'surgery' : 'शल्य चिकित्सा' ,
	'surprise' : 'आश्चर्य' ,
	'surprised' : 'स्तंभित होना' ,
	'surprising' : 'चौंका देने वाला' ,
	'surprisingly' : 'हैरानी की बात है' ,
	'surround' : 'चारों ओर से घेरना' ,
	'survey' : 'सर्वेक्षण' ,
	'survival' : 'जीवित रहना' ,
	'survive' : 'बच जाना' ,
	'survivor' : 'उत्तरजीवी' ,
	'suspect' : 'संदिग्ध व्यक्ति' ,
	'sustain' : 'बनाए रखना' ,
	'swear' : 'कसम खाता' ,
	'sweep' : 'झाड़ू लगा दो' ,
	'sweet' : 'मिठाई' ,
	'swim' : 'तैराकी' ,
	'swing' : 'झूला' ,
	'switch' : 'स्विच' ,
	'symbol' : 'प्रतीक' ,
	'symptom' : 'लक्षण' ,
	'system' : 'प्रणाली' ,
	'table' : 'टेबल' ,
	'tablespoon' : 'बड़ा चमचा' ,
	'tactic' : 'रणनीति' ,
	'tail' : 'पूंछ' ,
	'take' : 'लेना' ,
	'tale' : 'कहानी' ,
	'talent' : 'प्रतिभा' ,
	'talk' : 'बातचीत' ,
	'tall' : 'लंबा' ,
	'tank' : 'टैंक' ,
	'tap' : 'नल' ,
	'tape' : 'फीता' ,
	'target' : 'लक्ष्य' ,
	'task' : 'टास्क' ,
	'taste' : 'स्वाद' ,
	'tax' : 'कर' ,
	'taxpayer' : 'करदाता' ,
	'tea' : 'चाय' ,
	'teach' : 'सिखाना' ,
	'teacher' : 'अध्यापक' ,
	'teaching' : 'शिक्षण' ,
	'team' : 'टीम' ,
	'tear' : 'आँसू' ,
	'teaspoon' : 'छोटी चम्मच' ,
	'technical' : 'तकनीकी' ,
	'technique' : 'तकनीक' ,
	'technology' : 'प्रौद्योगिकी' ,
	'teen' : 'किशोर' ,
	'teenager' : 'किशोर' ,
	'telephone' : 'TELEPHONE' ,
	'telescope' : 'दूरबीन' ,
	'television' : 'टेलीविजन' ,
	'tell' : 'बताना' ,
	'temperature' : 'तापमान' ,
	'temporary' : 'अस्थायी' ,
	'ten' : 'दस' ,
	'tend' : 'प्रवृत्त होना' ,
	'tendency' : 'प्रवृत्ति' ,
	'tennis' : 'टेनिस' ,
	'tension' : 'तनाव' ,
	'tent' : 'तंबू' ,
	'term' : 'अवधि' ,
	'terms' : 'मामले' ,
	'terrible' : 'भयानक' ,
	'territory' : 'क्षेत्र' ,
	'terror' : 'आतंक' ,
	'terrorism' : 'आतंक' ,
	'terrorist' : 'आतंकवादी' ,
	'test' : 'परीक्षा' ,
	'testify' : 'गवाही देना' ,
	'testimony' : 'गवाही' ,
	'testing' : 'परिक्षण' ,
	'text' : 'मूलपाठ' ,
	'than' : 'से' ,
	'thank' : 'धन्यवाद' ,
	'thanks' : 'धन्यवाद' ,
	'that' : 'वह' ,
	'the' : '' ,
	'theater' : 'थिएटर' ,
	'their' : 'उनका' ,
	'them' : 'उन्हें' ,
	'theme' : 'विषय' ,
	'themselves' : 'खुद' ,
	'then' : 'फिर' ,
	'theory' : 'सिद्धांत' ,
	'therapy' : 'चिकित्सा' ,
	'there' : 'वहां' ,
	'therefore' : 'इसलिए' ,
	'these' : 'इन' ,
	'they' : 'वे' ,
	'thick' : 'मोटा' ,
	'thin' : 'पतला' ,
	'thing' : 'चीज़' ,
	'think' : 'सोच' ,
	'thinking' : 'विचारधारा' ,
	'third' : 'तीसरा' ,
	'thirty' : 'तीस' ,
	'this' : 'यह' ,
	'those' : 'वे' ,
	'though' : 'यद्यपि' ,
	'thought' : 'विचार' ,
	'threat' : 'धमकी' ,
	'threaten' : 'धमकाना' ,
	'three' : 'तीन' ,
	'throat' : 'गला' ,
	'through' : 'के माध्यम से' ,
	'throughout' : 'हर जगह' ,
	'throw' : 'फेंकना' ,
	'thus' : 'इस प्रकार' ,
	'ticket' : 'टिकट' ,
	'tie' : 'गुलोबन्द' ,
	'tight' : 'तंग' ,
	'time' : 'समय' ,
	'tiny' : 'छोटा' ,
	'tip' : 'टिप' ,
	'tire' : 'टायर' ,
	'tired' : 'थका हुआ' ,
	'tissue' : 'ऊतक' ,
	'title' : 'शीर्षक' ,
	'to' : 'प्रति' ,
	'tobacco' : 'तंबाकू' ,
	'today' : 'आज' ,
	'toe' : 'पैर की अंगुली' ,
	'together' : 'एक साथ' ,
	'tomato' : 'टमाटर' ,
	'tomorrow' : 'आने वाला कल' ,
	'tone' : 'सुर' ,
	'tongue' : 'जुबान' ,
	'tonight' : 'आज की रात' ,
	'too' : 'बहुत' ,
	'tool' : 'साधन' ,
	'tooth' : 'दांत' ,
	'top' : 'ऊपर' ,
	'topic' : 'विषय' ,
	'toss' : 'टॉस' ,
	'total' : 'संपूर्ण' ,
	'totally' : 'पूरी तरह से' ,
	'touch' : 'स्पर्श' ,
	'tough' : 'कठोर' ,
	'tour' : 'यात्रा' ,
	'tourist' : 'पर्यटक' ,
	'tournament' : 'टूर्नामेंट' ,
	'toward' : 'की ओर' ,
	'towards' : 'की ओर' ,
	'tower' : 'मीनार' ,
	'town' : 'नगर' ,
	'toy' : 'खिलौने' ,
	'trace' : 'निशान' ,
	'track' : 'संकरा रास्ता' ,
	'trade' : 'व्यापार' ,
	'tradition' : 'परंपरा' ,
	'traditional' : 'परंपरागत' ,
	'traffic' : 'यातायात' ,
	'tragedy' : 'त्रासदी' ,
	'trail' : 'रास्ता' ,
	'train' : 'रेल गाडी' ,
	'training' : 'प्रशिक्षण' ,
	'transfer' : 'स्थानांतरण' ,
	'transform' : 'परिवर्तन' ,
	'transformation' : 'परिवर्तन' ,
	'transition' : 'संक्रमण' ,
	'translate' : 'अनुवाद करना' ,
	'transportation' : 'परिवहन' ,
	'travel' : 'यात्रा' ,
	'treat' : 'इलाज' ,
	'treatment' : 'इलाज' ,
	'treaty' : 'संधि' ,
	'tree' : 'पेड़' ,
	'tremendous' : 'अद्भुत' ,
	'trend' : 'ट्रेंड' ,
	'trial' : 'परीक्षण' ,
	'tribe' : 'जनजाति' ,
	'trick' : 'छल' ,
	'trip' : 'यात्रा' ,
	'trouble' : 'मुसीबत' ,
	'truck' : 'ट्रक' ,
	'true' : 'सच' ,
	'truly' : 'सही मायने में' ,
	'trust' : 'विश्वास' ,
	'truth' : 'सत्य' ,
	'try' : 'कोशिश करो' ,
	'tube' : 'ट्यूब' ,
	'tunnel' : 'सुरंग' ,
	'turn' : 'मोड़' ,
	'TV' : 'टीवी' ,
	'twelve' : 'बारह' ,
	'twenty' : 'बीस' ,
	'twice' : 'दो बार' ,
	'twin' : 'जुड़वां' ,
	'two' : 'दो' ,
	'type' : 'प्रकार' ,
	'typical' : 'ठेठ' ,
	'typically' : 'आम तौर पर' ,
	'ugly' : 'कुरूप' ,
	'ultimate' : 'परम' ,
	'ultimately' : 'अंत में' ,
	'unable' : 'असमर्थ' ,
	'uncle' : 'चाचा' ,
	'under' : 'अंतर्गत' ,
	'undergo' : 'गुज़रना' ,
	'understand' : 'समझ गए' ,
	'understanding' : 'समझ' ,
	'unfortunately' : 'दुर्भाग्य से' ,
	'uniform' : 'वर्दी' ,
	'union' : 'संघ' ,
	'unique' : 'अनोखा' ,
	'unit' : 'इकाई' ,
	'United' : 'यूनाइटेड' ,
	'universal' : 'सार्वभौमिक' ,
	'universe' : 'ब्रम्हांड' ,
	'university' : 'विश्वविद्यालय' ,
	'unknown' : 'अनजान' ,
	'unless' : 'जब तक' ,
	'unlike' : 'भिन्न' ,
	'unlikely' : 'संभावना नहीं' ,
	'until' : 'जब तक' ,
	'unusual' : 'असामान्य' ,
	'up' : 'यूपी' ,
	'upon' : 'के ऊपर' ,
	'upper' : 'अपर' ,
	'urban' : 'शहरी' ,
	'urge' : 'विनती करना' ,
	'us' : 'हम' ,
	'use' : 'उपयोग' ,
	'used' : 'उपयोग किया गया' ,
	'useful' : 'उपयोगी' ,
	'user' : 'उपयोगकर्ता' ,
	'usual' : 'सामान्य' ,
	'usually' : 'आमतौर पर' ,
	'utility' : 'उपयोगिता' ,
	'vacation' : 'छुट्टी' ,
	'valley' : 'घाटी' ,
	'valuable' : 'मूल्यवान' ,
	'value' : 'मूल्य' ,
	'variable' : 'चर' ,
	'variation' : 'उतार - चढ़ाव' ,
	'variety' : 'विविधता' ,
	'various' : 'विभिन्न' ,
	'vary' : 'अलग होना' ,
	'vast' : 'व्यापक' ,
	'vegetable' : 'सबजी' ,
	'vehicle' : 'वाहन' ,
	'venture' : 'उद्यम' ,
	'version' : 'संस्करण' ,
	'versus' : 'बनाम' ,
	'very' : 'बहुत' ,
	'vessel' : 'पतीला' ,
	'veteran' : 'अनुभवी व्यक्ति' ,
	'via' : 'के जरिए' ,
	'victim' : 'शिकार' ,
	'victory' : 'विजय' ,
	'video' : 'वीडियो' ,
	'view' : 'दृश्य' ,
	'viewer' : 'दर्शक' ,
	'village' : 'गाँव' ,
	'violation' : 'उल्लंघन' ,
	'violence' : 'हिंसा' ,
	'violent' : 'हिंसक' ,
	'virtually' : 'आभासी रूप से' ,
	'virtue' : 'नैतिक गुण' ,
	'virus' : 'वाइरस' ,
	'visible' : 'दृश्यमान' ,
	'vision' : 'दृष्टि' ,
	'visit' : 'मुलाकात' ,
	'visitor' : 'आगंतुक' ,
	'visual' : 'दृश्य' ,
	'vital' : 'महत्वपूर्ण' ,
	'voice' : 'आवाज़' ,
	'volume' : 'आयतन' ,
	'volunteer' : 'स्वयंसेवक' ,
	'vote' : 'वोट' ,
	'voter' : 'मतदाता' ,
	'vs' : 'बनाम' ,
	'vulnerable' : 'चपेट में' ,
	'wage' : 'वेतन' ,
	'wait' : 'रुको' ,
	'wake' : 'जागना' ,
	'walk' : 'टहल लो' ,
	'wall' : 'दीवार' ,
	'wander' : 'विचलन' ,
	'want' : 'चाहते हैं' ,
	'war' : 'युद्ध' ,
	'warm' : 'गरम' ,
	'warn' : 'चेतावनी देना' ,
	'warning' : 'चेतावनी' ,
	'wash' : 'धुलाई' ,
	'waste' : 'बेकार' ,
	'watch' : 'घड़ी' ,
	'water' : 'पानी' ,
	'wave' : 'लहर' ,
	'way' : 'रास्ता' ,
	'we' : 'हम' ,
	'weak' : 'कमज़ोर' ,
	'wealth' : 'संपदा' ,
	'wealthy' : 'धनी' ,
	'weapon' : 'हथियार' ,
	'wear' : 'घिसाव' ,
	'weather' : 'मौसम' ,
	'wedding' : 'शादी' ,
	'week' : 'सप्ताह' ,
	'weekend' : 'सप्ताहांत' ,
	'weekly' : 'साप्ताहिक' ,
	'weigh' : 'तौलना' ,
	'weight' : 'वजन' ,
	'welcome' : 'स्वागत हे' ,
	'welfare' : 'कल्याण' ,
	'well' : 'कुंआ' ,
	'west' : 'पश्चिम' ,
	'western' : 'वेस्टर्न' ,
	'wet' : 'गीला' ,
	'what' : 'क्या' ,
	'whatever' : 'जो भी हो' ,
	'wheel' : 'पहिया' ,
	'when' : 'कब' ,
	'whenever' : 'जब कभी' ,
	'where' : 'कहाँ पे' ,
	'whereas' : 'जबकि' ,
	'whether' : 'चाहे' ,
	'which' : 'कौन कौन से' ,
	'while' : 'जबकि' ,
	'whisper' : 'फुसफुसाना' ,
	'white' : 'सफेद' ,
	'who' : 'who' ,
	'whole' : 'पूरा का पूरा' ,
	'whom' : 'किसको' ,
	'whose' : 'किसका' ,
	'why' : 'क्यों' ,
	'wide' : 'चौड़ा' ,
	'widely' : 'व्यापक रूप से' ,
	'widespread' : 'बड़े पैमाने पर' ,
	'wife' : 'बीवी' ,
	'wild' : 'जंगली' ,
	'will' : 'मर्जी' ,
	'willing' : 'इच्छुक' ,
	'win' : 'जीत' ,
	'wind' : 'हवा' ,
	'window' : 'खिड़की' ,
	'wine' : 'वाइन' ,
	'wing' : 'विंग' ,
	'winner' : 'विजेता' ,
	'winter' : 'सर्दी' ,
	'wipe' : 'पोंछना' ,
	'wire' : 'वायर' ,
	'wisdom' : 'बुद्धि' ,
	'wise' : 'ढंग' ,
	'wish' : 'तमन्ना' ,
	'with' : 'साथ' ,
	'withdraw' : 'निकालना' ,
	'within' : 'अंदर' ,
	'without' : 'बिना' ,
	'witness' : 'साक्षी' ,
	'woman' : 'महिला' ,
	'wonder' : 'आश्चर्य' ,
	'wonderful' : 'प्रशंसनीय' ,
	'wood' : 'लकड़ी' ,
	'wooden' : 'लकड़ी का' ,
	'word' : 'शब्द' ,
	'work' : 'काम' ,
	'worker' : 'मज़दूर' ,
	'working' : 'काम कर रहे' ,
	'works' : 'काम करता है' ,
	'workshop' : 'कार्यशाला' ,
	'world' : 'दुनिया' ,
	'worried' : 'चिंतित' ,
	'worry' : 'चिंता' ,
	'worth' : 'लायक' ,
	'would' : 'चाहेंगे' ,
	'wound' : 'घाव' ,
	'wrap' : 'चादर' ,
	'write' : 'लिखो' ,
	'writer' : 'लेखक' ,
	'writing' : 'लिखना' ,
	'wrong' : 'गलत' ,
	'yard' : 'यार्ड' ,
	'yeah' : 'हां' ,
	'year' : 'वर्ष' ,
	'yell' : 'चिल्लाना' ,
	'yellow' : 'पीला' ,
	'yes' : 'हां' ,
	'yesterday' : 'बीता हुआ कल' ,
	'yet' : 'अभी तक' ,
	'yield' : 'उपज' ,
	'you' : 'आप' ,
	'young' : 'युवा' ,
	'your' : 'आपका' ,
	'yours' : 'आपका अपना' ,
	'yourself' : 'स्वयं' ,
	'youth' : 'युवा' ,
	'zone' : 'क्षेत्र' ,
	'adjust' : 'समायोजित करना' ,
	'adviser' : 'सलाहकार' ,
	'ban' : 'ban' ,
	'die' : 'मरना' ,
	'dig' : 'गड्ढा करना' ,
	'e-mail' : 'ईमेल' ,
	'mm-hmm' : 'मिमी-हम्म' ,
	'pour' : 'बहना' ,
	'sin' : 'पाप' ,
	'single' : 'एक' ,
	'sink' : 'हौज' ,
	'sir' : 'महोदय' ,
	'sister' : 'बहन' ,
	'sit' : 'बैठिये' ,
	'site' : 'स्थल' ,
	'situation' : 'परिस्थिति' ,
	'six' : 'छह' ,
	'size' : 'आकार' ,
	'skin' : 'त्वचा' ,
	'sky' : 'आकाश' ,
	'slave' : 'दास' ,
	'solve' : 'का समाधान' ,
	'some' : 'कुछ' ,
	'somebody' : 'कोई' ,
	'somehow' : 'किसी न किसी तरह' ,
	'someone' : 'कोई व्यक्ति' ,
	'something' : 'कोई चीज़' ,
	'sometimes' : 'कभी - कभी' ,
	'thousand' : 'हज़ार' ,
	'troop' : 'सेना' ,
	'violate' : 'का उल्लंघन' ,
}