network =   {
                "ET" : "Etisalat India",
                "SR" : "Subrin Rintel",
                "ST" : "S Tel",
                "LM" : "Loop Mobile",
                "RC" : "Reliance Mobile CDMA",
                "VD" : "Videocon Telecom",
                "MT" : "MTS India",
                "RG" : "Reliance Mobile GSM",
                "AC" : "AIRCEL",
                "TD" : "TATA DOCOMO",
                "TN" : "telenor",
                "AT" : "Airtel India",
                "CG" : "BSNL Mobile",
                "DP" : "MTNL (DOLPHIN)",
                "AV" : "AEROVOYCE (MNVO Type)",
                "RJ" : "Reliance Jio",
                "VI" : "Vodafone Idea",
                "@@" : "Undefined Data"
            }
state =    {
                "JK" : "Jammu and Kashmir",
                "UW" : "UP (West)",
                "WB" : "West Bengal",
                "DL" : "Delhi",
                "RJ" : "Rajasthan",
                "TN" : "Tamil Nadu",
                "OR" : "Odisha",
                "PB" : "Punjab",
                "MP" : "Madhya Pradesh & Chhattisgarh",
                "MH" : "Maharashtra & Goa",
                "KA" : "Karnataka",
                "KL" : "Kerala & Lakshadweep",
                "HR" : "Haryana",
                "HP" : "Himachal Pradesh",
                "BR" : "Bihar & Jharkhand",
                "GJ" : "Gujarat",
                "NE" : "North East",
                "AS" : "Assam",
                "MU" : "Mumbai",
                "AP" : "Andhra Pradesh & Telangana",
                "UE" : "UP (East)",
                "KO" : "Kolkata",
                "@@" : "Undefined Data"
        }